import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';import {createDatabase} from '../database.mjs';import worker from '../generated/worker.mjs';
test('advisor access is isolated and only administrators can share or assign',async()=>{const pg=new PGlite();try{await pg.exec(readFileSync(new URL('../generated/schema.sql',import.meta.url),'utf8'));const db=createDatabase({query:(...a)=>pg.query(...a),connect:async()=>({query:(...a)=>pg.query(...a),release(){}})});const call=async(user,path,method='GET',body)=>worker.fetch(new Request('https://prospectpilot.io'+path,{method,headers:{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.com','content-type':typeof body==='string'?'text/csv':'application/json'},...(body?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}),{DB:db});
await call('admin','/api/me');await call('owner','/api/me');await call('stranger','/api/me');
const imported=await call('owner','/api/v3/discovery/imports/csv','POST','First Name,Last Name,Company,Title,Email\nJane,Smith,Audit Body Shop,Owner,jane@example.com');assert.equal(imported.status,201);
const listed=await (await call('owner','/api/v3/discovery/leads')).json();assert.equal(listed.total,1);const id=listed.leads[0].id;
assert.equal((await (await call('stranger','/api/v3/discovery/leads')).json()).total,0);assert.equal((await call('stranger','/api/v3/discovery/leads/'+id)).status,404);
for(const action of ['update','delete','assign']){const result=await (await call('stranger','/api/v3/discovery/leads/bulk','PATCH',{action,lead_ids:[id],follow_up_status:'Contacted',advisor_email:'stranger@example.com'})).json();assert.equal(result.result.updated,0);assert.equal(result.result.skipped,1);}
const denied=await (await call('owner','/api/v3/discovery/leads/bulk','PATCH',{action:'share',lead_ids:[id],advisor_email:'stranger@example.com'})).json();assert.equal(denied.result.updated,0);
const shared=await (await call('admin','/api/v3/discovery/leads/bulk','PATCH',{action:'share',lead_ids:[id],advisor_email:'stranger@example.com'})).json();assert.equal(shared.result.updated,1);assert.equal((await (await call('stranger','/api/v3/discovery/leads')).json()).total,1);
const retained=await (await call('stranger','/api/v3/discovery/leads/bulk','PATCH',{action:'delete',lead_ids:[id]})).json();assert.equal(retained.result.updated,0);assert.equal((await call('owner','/api/v3/discovery/leads/'+id)).status,200);
}finally{await pg.close();}});
