import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {createResearchLab} from '../research-lab.mjs';
import {assessLead} from '../lead-quality.mjs';
import {nextAction,workflowSignature} from '../advisor-workflow.mjs';
const now=new Date('2026-09-12T15:00:00Z');
const lead={id:'fixture',first_name:'Jamie',last_name:'Rivera',company:'Example Manufacturing',email:'jamie@example.com',estimated_age_range:'62',country:'US'};
const csv='First Name,Last Name,Company,Title,Email,Estimated Age Range,Country\nJamie,Rivera,Example Manufacturing,Director,jamie@example.com,62,US';
async function fixture(){const db=new PGlite();for(const file of ['generated/schema.sql','migrations/006-research-lab.sql','migrations/007-quality-v2.sql','migrations/008-prospect-workspace.sql','migrations/012-plan-catalog-summary.sql','migrations/013-advisor-workflow.sql'])await db.exec(readFileSync(new URL('../'+file,import.meta.url),'utf8'));const pool={query:(...a)=>db.query(...a),connect:async()=>({query:(...a)=>db.query(...a),release(){}})};const user={uid:'owner',email:'owner@example.com'},lab=createResearchLab({pool,now:()=>now,sources:{readiness:{}}});await lab.importCSV(user,{csv});const id=(await lab.list(user)).leads[0].lead.id;return {db,lab,user,id};}
async function reviewBasics(lab,user,id){const d=await lab.detail(user,id);for(const [field,value] of Object.entries({age:{min:62,max:62},residence:{country:'US',scope:'residence'},contact:{channel:'email',address:'jamie@example.com',identity_confirmed:true}}))await lab.review(user,id,{field,value,verdict:'confirmed',source:'Synthetic authorized fixture',note:'Synthetic evidence only.',observed_at:now.toISOString(),identity_signature:d.quality.identity_signature});}
test('next actions never equate contact details or financial estimates with verified qualification',()=>{const q=assessLead(lead,[],{now});assert.equal(nextAction(lead,q,now).bucket,'review');assert.equal(nextAction(lead,q,now).contact,null);const noContact={...lead,email:''};assert.equal(nextAction(noContact,assessLead(noContact,[],{now}),now).bucket,'enrich');const dnc={...lead,suppressed:true,follow_up_date:'2026-09-01T12:00:00Z'};assert.equal(nextAction(dnc,assessLead(dnc,[],{now}),now).bucket,'closed');assert.equal(nextAction({...lead,follow_up_status:'Not a Fit'},q,now).bucket,'closed');});
test('worklist uses live evidence, prioritizes due work, and supports full-name search',async()=>{const {db,lab,user,id}=await fixture();try{await reviewBasics(lab,user,id);let work=await lab.advisor.worklist(user,{view:'ready',search:'Jamie Rivera'});assert.equal(work.total,1);assert.notEqual(work.items[0].quality.status,'verified');assert.equal(work.items[0].action.contact.address,'jamie@example.com');await db.query(`UPDATE discovery_leads SET payload=jsonb_set(payload::jsonb,'{follow_up_date}','"2026-09-10T10:00:00Z"')::text WHERE id=$1`,[id]);work=await lab.advisor.worklist(user,{view:'due'});assert.equal(work.total,1);assert.equal(work.items[0].action.rank,0);await db.query(`UPDATE lab_observations SET payload=jsonb_set(payload,'{observed_at}','"2020-01-01"') WHERE lead_id=$1 AND field='contact'`,[id]);assert.equal((await lab.advisor.worklist(user,{view:'due'})).items[0].action.contact,null);assert.equal((await lab.advisor.worklist(user,{search:'missing'})).total,0);}finally{await db.close();}});
test('outcomes persist to legacy workflow, replay safely, detect conflicts, and enforce ownership',async()=>{const {db,lab,user,id}=await fixture();try{let detail=await lab.advisor.detail(user,id);const input={outcome:'follow_up',note:'Asked to discuss goals next week.',next_at:'2026-09-15T14:00:00Z',signature:detail.action.signature,idempotency_key:'follow-1'};await lab.advisor.save(user,id,input);assert.equal((await lab.advisor.save(user,id,input)).replayed,true);const saved=(await lab.detail(user,id)).lead;assert.equal(saved.follow_up_status,'Follow-up');assert.equal(saved.follow_up_date,new Date(input.next_at).toISOString());assert.match(saved.notes,/goals next week/);assert.equal((await lab.advisor.worklist(user,{view:'scheduled'})).total,1);assert.equal((await lab.advisor.detail(user,id)).activities.length,1);await assert.rejects(lab.advisor.save(user,id,{...input,idempotency_key:'stale'}),{status:409});const other={uid:'other',email:'other@example.com'};assert.equal((await lab.advisor.worklist(other)).total,0);await assert.rejects(lab.advisor.detail(other,id),{status:404});await assert.rejects(lab.advisor.save(other,id,input),{status:404});await assert.rejects(lab.advisor.exportEnrichment(other,{ids:[id]}),{status:404});detail=await lab.advisor.detail(user,id);await assert.rejects(lab.advisor.save(user,id,{...input,signature:detail.action.signature,idempotency_key:'bad-time',next_at:'2026-09-01'}),{status:422});assert.notEqual(detail.action.signature,input.signature);assert.equal(detail.action.signature,workflowSignature(saved));}finally{await db.close();}});
test('meeting metrics count people once and suppression removes shortcuts and exports without allowing reopening',async()=>{const {db,lab,user,id}=await fixture();try{await reviewBasics(lab,user,id);for(const n of [1,2]){const d=await lab.advisor.detail(user,id);await lab.advisor.save(user,id,{outcome:'meeting_booked',signature:d.action.signature,idempotency_key:'meeting-'+n,next_at:'2026-09-15T14:00:00Z'});}let work=await lab.advisor.worklist(user,{view:'meetings'});assert.equal(work.total,1);assert.equal(work.activity.meetings,1);assert.equal(work.activity.conversations,2);let d=await lab.advisor.detail(user,id);await lab.advisor.save(user,id,{outcome:'do_not_contact',signature:d.action.signature,idempotency_key:'dnc',note:'Asked not to be contacted.'});d=await lab.advisor.detail(user,id);assert.equal(d.action.contact,null);assert.equal(d.action.bucket,'closed');await assert.rejects(lab.advisor.save(user,id,{outcome:'reopen',signature:d.action.signature,idempotency_key:'cannot-reopen'}),{status:422});assert.equal((await lab.advisor.exportEnrichment(user,{ids:[id]})).headers.get('content-type'),'text/csv; charset=utf-8');assert.doesNotMatch(await (await lab.advisor.exportEnrichment(user,{ids:[id]})).text(),/Jamie/);await db.query('DELETE FROM discovery_leads WHERE id=$1',[id]);assert.equal((await db.query('SELECT * FROM advisor_activities')).rows.length,0);}finally{await db.close();}});
test('provider export contains only matching identifiers and research task, with spreadsheet formula protection',async()=>{const {db,lab,user,id}=await fixture();try{await db.query(`UPDATE discovery_leads SET payload=jsonb_set(payload::jsonb,'{first_name}','"=HYPERLINK(test)"')::text WHERE id=$1`,[id]);const response=await lab.advisor.exportEnrichment(user,{ids:[id]});const text=await response.text();assert.match(text,/"'=HYPERLINK/);assert.match(text,/Company Name/);assert.doesNotMatch(text,/lower_bound_usd|consent_confirmed|jamie@example.com/);}finally{await db.close();}});
test('directory handoff is owned and replay-safe; suppression stays effective in both workspaces',async()=>{const {db,lab,user,id}=await fixture();try{
 await db.query('INSERT INTO prospect_contacts(id,user_id,payload) VALUES($1,$2,$3::jsonb)',['contact',user.uid,JSON.stringify({...lead,title:'Director',source:'Synthetic professional export'})]);
 let result=await lab.importContacts(user,{ids:['contact']});assert.equal(result.linked,1);assert.equal((await lab.importContacts(user,{ids:['contact']})).replayed,true);
 const linked=(await db.query('SELECT lead_id FROM advisor_contact_links WHERE contact_id=$1',['contact'])).rows[0].lead_id;
 await reviewBasics(lab,user,linked);assert.equal((await lab.advisor.detail(user,linked)).action.bucket,'ready');
 await db.query(`UPDATE prospect_contacts SET payload=jsonb_set(payload,'{suppressed}','true') WHERE id='contact'`);
 assert.equal((await lab.advisor.detail(user,linked)).action.contact,null);assert.equal((await lab.detail(user,linked)).quality.status,'excluded');
 const work=await lab.advisor.worklist(user,{view:'closed'});assert.ok(work.items.some(r=>r.lead.id===linked));
 await assert.rejects(lab.importContacts({uid:'stranger',email:'stranger@example.com'},{ids:['contact']}),{status:404});
 await db.query(`UPDATE prospect_contacts SET payload=jsonb_set(payload,'{suppressed}','false') WHERE id='contact'`);
 const d=await lab.advisor.detail(user,linked);await lab.advisor.save(user,linked,{outcome:'do_not_contact',signature:d.action.signature,idempotency_key:'linked-dnc'});
 assert.equal((await db.query("SELECT payload->>'suppressed' AS suppressed FROM prospect_contacts WHERE id='contact'")).rows[0].suppressed,'true');
}finally{await db.close();}});
