import test from 'node:test';import assert from 'node:assert/strict';
import {createHandler} from '../handler.mjs';
const origin='https://prospectpilot.io',email='dst@financialplannersofamerica.com';
const claims={uid:'verified-owner',email,email_verified:true,auth_time:Math.floor(Date.now()/1000),firebase:{sign_in_provider:'google.com'}};
const setup=(overrides={})=>{let seen;const auth={verifyIdToken:async token=>{if(token!=='valid')throw Error();return {...claims,...overrides}},createSessionCookie:async()=> 'signed-session',verifySessionCookie:async cookie=>{if(cookie!=='signed-session')throw Error();return {...claims,...overrides}}};const handler=createHandler({auth,db:{},worker:{fetch:async request=>{seen=request;return Response.json({ok:true})}},loginHtml:'login',loginScript:'script',ownerEmail:email,origins:[origin]});return {handler,getSeen:()=>seen};};
const req=(path,init={})=>new Request(origin+path,init);
test('untrusted identity headers cannot authenticate',async()=>{const {handler}=setup();assert.equal((await handler(req('/api/me',{headers:{'oai-authenticated-user-id':'fake','oai-authenticated-user-email':email}}))).status,401);});
test('unverified, unsupported and stale identities cannot create sessions',async()=>{for(const overrides of [{email_verified:false},{firebase:{sign_in_provider:'anonymous'}},{auth_time:0},{uid:''}]){const {handler}=setup(overrides);assert.ok((await handler(req('/auth/session',{method:'POST',headers:{origin},body:JSON.stringify({idToken:'valid'})}))).status>=400);}});
test('valid session is secure and does not trust client identity',async()=>{const {handler,getSeen}=setup();const response=await handler(req('/auth/session',{method:'POST',headers:{origin},body:JSON.stringify({idToken:'valid'})}));assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);const result=await handler(req('/api/me',{headers:{cookie:'__session=signed-session','oai-authenticated-user-id':'fake'}}));assert.equal(result.status,200);assert.equal(getSeen().headers.get('oai-authenticated-user-id'),'verified-owner');assert.equal(result.headers.get('cache-control'),'private, no-store');});
test('cross-site writes and invalid origins rejected',async()=>{const {handler}=setup();for(const origin of ['https://evil.example',''])assert.equal((await handler(req('/auth/session',{method:'POST',headers:{origin},body:'{}'}))).status,403);assert.equal((await handler(new Request('https://evil.example/api/me'))).status,403);});
test('revoked session fails closed',async()=>{const {handler}=setup();assert.equal((await handler(req('/api/me',{headers:{cookie:'__session=expired'}}))).status,401);});

test('any verified Google or password account can create a session without owner approval',async()=>{
 for(const provider of ['google.com','password']){const {handler}=setup({uid:'new-user',email:'new-user@example.net',firebase:{sign_in_provider:provider}});const response=await handler(req('/auth/session',{method:'POST',headers:{origin},body:JSON.stringify({idToken:'valid'})}));assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/HttpOnly; Secure/);}
});
test('public accounts cannot reach legacy administrative tools',async()=>{const {handler,getSeen}=setup({uid:'new-user',email:'new-user@example.net'});assert.equal((await handler(req('/api/me',{headers:{cookie:'__session=signed-session'}}))).status,403);assert.equal(getSeen(),undefined);});
