import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';import {createDatabase} from '../database.mjs';import worker,{RESEARCH_SOURCES,researchRecord,researchCSV,researchMatch,researchMWBE} from '../generated/worker.mjs';
const lead={first_name:'Jane',last_name:'Smith',company:'Example Consulting',location:'Albany, NY'};
test('all 12 sources produce scoped provenance without qualification claims',()=>{assert.equal(RESEARCH_SOURCES.length,12);for(const source of RESEARCH_SOURCES){const r=researchRecord(lead,{source:source.id,url:'https://example.com/record',excerpt:'Jane Smith works at Example Consulting in Albany, NY.',source_date:'2026-09-01'});assert.equal(r.scope,source.scope);assert.equal(r.status,'reviewed_by_user');assert.equal(r.priority_score,undefined);}assert.throws(()=>researchRecord(lead,{source:'warn',url:'https://example.com/',excerpt:'Example Consulting notice'}),/notice date/);assert.equal(researchMatch(lead,'Jane Smith at Unrelated Business','person'),false);assert.equal(researchMatch(lead,'Example Consulting announcement','company'),true);assert.equal(researchMatch(lead,'Example Consultinghouse announcement','company'),false);});
test('research CSV handles quotes and rejects malformed rows',()=>{assert.equal(researchCSV('Company,Notice\n"Example, Inc",2026-09-01')[0].Company,'Example, Inc');assert.throws(()=>researchCSV('Company,Notice\n"Unfinished'),/quote/);assert.throws(()=>researchCSV('Company,Company\nA,B'),/unique/);});
test('research save is owned, idempotent and does not change qualification',async()=>{const pg=new PGlite();try{await pg.exec(readFileSync(new URL('../generated/schema.sql',import.meta.url),'utf8'));const db=createDatabase({query:(...a)=>pg.query(...a),connect:async()=>({query:(...a)=>pg.query(...a),release(){}})});const call=async(path,body,user='owner')=>worker.fetch(new Request('https://prospectpilot.io/api/'+path,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.com','content-type':'application/json'},...(body?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}),{DB:db});await call('me');const imp=await call('v3/discovery/imports/csv','First Name,Last Name,Company,Title,Email\nJane,Smith,Example Consulting,Owner,jane@example.com');assert.equal(imp.status,201);const lists=await (await call('research/leads')).json();const id=lists.leads[0].id;const before=(await pg.query('SELECT payload FROM discovery_leads WHERE id=$1',[id])).rows[0].payload;
const body={lead_id:id,source:'warn',url:'https://dol.ny.gov/warn-dashboard',excerpt:'Example Consulting filed a WARN notice.',source_date:'2026-09-01'};const saved=await call('research/save',body);assert.equal(saved.status,200,await saved.clone().text());assert.equal((await (await call('research/save',body)).json()).duplicate,true);assert.equal((await call('research/save',body,'stranger')).status,404);const after=JSON.parse((await pg.query('SELECT payload FROM discovery_leads WHERE id=$1',[id])).rows[0].payload);assert.equal(after.research_records.length,1);delete after.research_records;assert.deepEqual(after,JSON.parse(before));const preview=await (await call('research/preview',{lead_id:id,source:'warn',csv:'Company,Notice Date\nExample Consulting,2026-09-01\nUnrelated Business,2026-09-01'})).json();assert.equal(preview.total,1);
const originalFetch=globalThis.fetch;try{globalThis.fetch=async target=>String(target).endsWith('/robots.txt')?new Response('User-agent: *\nAllow: /',{headers:{'content-type':'text/plain'}}):new Response('<p>Jane Smith works at Example Consulting.</p>',{headers:{'content-type':'text/html'}});const page=await (await call('research/preview',{lead_id:id,source:'website',url:'https://example.com/team'})).json();assert.equal(page.method,'fetched_page');assert.equal(page.match,true);}finally{globalThis.fetch=originalFetch;}

}finally{await pg.close();}});

test('MWBE connector requests a restricted projection and drops demographic fields',async()=>{const before=globalThis.fetch;try{globalThis.fetch=async url=>{const u=new URL(url);assert.equal(u.hostname,'data.cityofnewyork.us');assert.ok(!u.searchParams.get('$select').includes('ethnicity'));return new Response(JSON.stringify([{vendor_formal_name:'Example Consulting',first_name:'Jane',last_name:'Smith',certification:'WBE',ethnicity:'not returned',website:'https://example.com'}]));};const rows=await researchMWBE('consulting');assert.equal(rows[0].company,'Example Consulting');assert.equal(rows[0].ethnicity,undefined);}finally{globalThis.fetch=before;}});
