const $=id=>document.getElementById(id);
const labels={age:'Age 45–73',residence:'US residence',retirement:'Transfer eligibility',contact:'Contact route',net_worth:'Net worth ≥ $250K, home excluded'};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=value=>String(value||'').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const num=value=>Number(value||0).toLocaleString();
const dollars=value=>value==null?'—':Number(value).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const safeURL=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}};
const link=(url,text)=>safeURL(url)?`<a href="${esc(safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(text)}</a>`:esc(text);
const badge=(value)=>`<span class="badge ${esc(value)}">${esc(title(value))}</span>`;
let offset=0,total=0,leads=[],runs=[],current=null,busy=false,pollTimer=null,sourceReadiness=null,leadLoadVersion=0,leadDetailVersion=0,runDetailVersion=0;
const selected=new Set();
async function request(path,options={}) {
  const response=await fetch(path,{...options,headers:{'content-type':'application/json',...options.headers}});
  if(response.status===401){location.href='/login';throw Error('Please sign in.');}
  if(!response.ok){let data;try{data=await response.json();}catch{}throw Error(data?.detail||`Request failed (${response.status}).`);}
  return response.headers.get('content-type')?.includes('text/csv')?response.blob():response.json();
}
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function config(){return {employers:$('employers').value.split('\n').map(s=>s.trim()).filter(Boolean),websites:$('websites').value.split('\n').map(s=>s.trim()),states:$('states').value.split(/[,;\s]+/).filter(Boolean),sources:[...document.querySelectorAll('input[name="source"]:checked')].map(e=>e.value),max_companies:Number($('maxCompanies').value),daily_budget_micros:Math.round(Number($('budget').value)*1000000)};}
function readSettings(value){const c=value.configuration||{};$('employers').value=(c.employers||[]).join('\n');$('websites').value=(c.websites||[]).join('\n');$('states').value=(c.states||[]).join(', ');$('maxCompanies').value=c.max_companies||10;$('budget').value=Number(value.daily_budget_micros||0)/1000000;$('dailyEnabled').checked=value.daily_enabled===true;$('dailyHour').value=value.daily_hour??13;document.querySelectorAll('input[name="source"]').forEach(e=>{e.checked=(c.sources||['public_web','sec','warn']).includes(e.value);});}
function renderSummary(s){
  $('metricSourced').textContent=num(s.totals.new_sourced);$('metricVerified').textContent=num(s.totals.newly_verified);$('metricCpl').textContent=dollars(s.totals.cost_per_verified);$('metricDaily').textContent=s.totals.verified_per_calendar_day.toFixed(1);$('costBasis').textContent=`${dollars(s.totals.cost_usd)} recorded · other costs may be unrecorded`;
  const max=Math.max(1,...s.daily.flatMap(d=>[d.new_sourced,d.newly_verified]));$('dailyChart').replaceChildren();
  for(const d of s.daily){const column=document.createElement('div');column.className='chart-column';column.title=`${d.day}: ${d.new_sourced} sourced, ${d.newly_verified} verified, ${d.imported} imported`;const bars=document.createElement('div');bars.className='bars';for(const key of ['new_sourced','newly_verified']){const bar=document.createElement('div');bar.className=key==='newly_verified'?'bar verified':'bar';bar.style.height=`${Math.max(1,Number(d[key])/max*100)}%`;bars.append(bar);}const date=document.createElement('span');date.textContent=d.day.slice(5);column.append(bars,date);$('dailyChart').append(column);}
  $('inventory').innerHTML=s.inventory.map(i=>`<span class="badge ${esc(i.status)}">${esc(title(i.status))} · ${num(i.n)}</span>`).join('')||'<span class="muted">Your research inventory is empty.</span>';
  $('catalog').textContent=s.catalog.plans?`${num(s.catalog.plans)} distinct employer plans · ${num(s.catalog.filings)} filing records · latest plan year ${s.catalog.latest_plan_year}. Catalog loaded ${new Date(s.catalog.imported_at).toLocaleDateString()}; filing dates are recorded separately. These are employer records, not individual leads.`:'Employer-plan catalog not loaded yet. Start with named employers or import your existing leads.';
  $('sourceMetrics').innerHTML=s.sources.length?'<div class="table-wrap"><table><thead><tr><th>Source</th><th>Acquired</th><th>Qualified</th><th>Yield</th><th>Attempts / gaps</th><th>Reserved provider cost</th><th>Provider cost / qualified</th></tr></thead><tbody>'+s.sources.map(row=>`<tr><td>${esc(title(row.source))}</td><td>${num(row.acquired)}</td><td>${num(row.qualified)}</td><td>${row.qualification_rate==null?"—":(row.qualification_rate*100).toFixed(1)+"%"}</td><td>${num(row.attempts)} / ${num(row.gaps)}</td><td>${dollars(row.cost_micros==null?null:Number(row.cost_micros)/1000000)}</td><td>${dollars(row.reserved_cost_per_qualified)}</td></tr>`).join('')+'</tbody></table></div>':'<p class="empty">Run an experiment to compare source yield and cost.</p>';
}
function renderLeads(data){leads=data.leads;total=data.total;
  $('leadTable').innerHTML=leads.length?'<table><thead><tr><th><input id="selectPage" type="checkbox" aria-label="Select this page"></th><th>Prospect</th><th>Quality</th><th>Evidence</th><th>Criteria: age / US / assets / contact / net worth</th><th>Next review</th></tr></thead><tbody>'+leads.map(({lead:l,quality:q})=>`<tr><td><input type="checkbox" data-select="${esc(l.id)}" aria-label="Select ${esc(l.first_name)} ${esc(l.last_name)}" ${selected.has(l.id)?'checked':''}></td><td><button class="person-button" data-lead="${esc(l.id)}">${esc(l.first_name)} ${esc(l.last_name)}</button><small>${esc(l.current_title||'Title unknown')} · ${esc(l.company||'Employer unknown')}</small></td><td>${badge(q.status)}</td><td>${num(q.score)} / 100</td><td><div class="criteria">${Object.entries(q.gates).map(([key,g])=>`<span class="criterion ${esc(g.state)}" title="${esc(labels[key]+': '+g.reason)}">${g.state==='confirmed'?'✓':g.state==='candidate'?'~':g.state==='failed'?'×':'?'}</span>`).join('')}</div></td><td>${esc(labels[q.gaps[0]]||'Complete')}</td></tr>`).join('')+'</tbody></table>':'<p class="empty">No records in this view. Import candidates or run discovery to begin.</p>';
  document.querySelectorAll('[data-lead]').forEach(e=>e.onclick=()=>openLead(e.dataset.lead));document.querySelectorAll('[data-select]').forEach(e=>e.onchange=()=>{e.checked?selected.add(e.dataset.select):selected.delete(e.dataset.select);});
  if($('selectPage'))$('selectPage').onchange=e=>{leads.forEach(({lead})=>e.target.checked?selected.add(lead.id):selected.delete(lead.id));renderLeads(data);};
  $('pageInfo').textContent=total?`${num(offset+1)}–${num(Math.min(offset+50,total))} of ${num(total)} · assessed filter, live evidence`:'0 records';$('previous').disabled=offset===0;$('next').disabled=offset+50>=total;
}
async function loadLeads(){
  const version=++leadLoadVersion,query=new URLSearchParams({offset,limit:50,compact:'true',status:$('qualityFilter').value,search:$('search').value});
  try{const data=await request('/api/lab/leads?'+query);if(version!==leadLoadVersion)return;if(offset>0&&!data.leads.length&&data.total>0){const lastOffset=Math.floor((data.total-1)/50)*50;if(lastOffset!==offset){offset=lastOffset;return loadLeads();}}if(!data.total)offset=0;renderLeads(data);}
  catch(error){if(version===leadLoadVersion)throw error;}
}
function sourceIssues(run){return (run.source_results||[]).filter(t=>(t.errors||[]).length).map(t=>`<p class="muted"><strong>${esc(title(t.source))}${t.company?' · '+esc(t.company):''}:</strong> ${esc(t.errors.join(' '))}</p>`).join('');}
function renderRuns(data){runs=data.runs;$('runs').innerHTML=runs.length?runs.map(r=>`<div class="run"><div><strong>${esc(title(r.kind))}</strong> ${badge(r.status)}<small>${esc(new Date(r.created_at).toLocaleString())} · ${num(r.finished_tasks)}/${num(r.tasks)} checks · ${num(r.new_people)} new people</small>${r.kind==='discovery'&&!Number(r.new_people)&&!['queued','running'].includes(r.status)?'<p>No people were added. Review the source results below; this does not establish that no prospects exist.</p>':''}${sourceIssues(r)}</div><button class="secondary" data-run="${esc(r.id)}">Details</button></div>`).join(''):'<p class="empty">No experiments yet.</p>';
  document.querySelectorAll('[data-run]').forEach(e=>e.onclick=()=>openRun(e.dataset.run));

}
async function refresh(showNotice=true){
  if(busy)return;busy=true;clearTimeout(pollTimer);$('refresh').disabled=true;
  const sections=[['Summary',()=>request('/api/lab/summary').then(renderSummary)],['Run history',()=>request('/api/lab/runs').then(renderRuns)],['Lead results',loadLeads],['Next actions',loadWorklist]];
  try{
    const results=await Promise.allSettled(sections.map(([,load])=>load()));
    const failures=results.flatMap((r,i)=>r.status==='rejected'?[sections[i][0]+': '+r.reason.message]:[]);
    if(failures.length)notice('Some sections could not refresh. Successfully loaded results are shown. '+failures.join(' '),true);
    else if(showNotice)notice('Worklist updated. Open a prospect to review evidence and save the next step.');
  }finally{
    busy=false;$('refresh').disabled=false;
    if(!document.hidden&&runs.some(r=>['queued','running'].includes(r.status)))pollTimer=setTimeout(()=>refresh(false),8000);
  }
}
async function openLead(id){
  const version=++leadDetailVersion;current=null;currentWorkflow=null;$('saveReview').disabled=true;$('activityForm').hidden=true;$('conversationBrief').textContent='Loading the conversation brief…';$('contactActions').replaceChildren();$('activityHistory').replaceChildren();
  $('personName').textContent='Loading evidence…';$('personRole').textContent='';
  for(const name of ['personGates','personSources','personPlans','reviewError'])$(name).textContent='';
  $('reviewForm').reset();$('observedAt').value=new Date().toISOString().slice(0,10);$('observedAt').max=$('observedAt').value;reviewFields();
  if(!$('detail').open)$('detail').showModal();
  try{const data=await request('/api/lab/leads/'+encodeURIComponent(id));if(version!==leadDetailVersion)return;current=data;renderPerson();$('saveReview').disabled=false;await loadActivity(id,version);}
  catch(e){if(version===leadDetailVersion){$('personName').textContent='Evidence unavailable';$('reviewError').textContent=e.message;}}
}
function renderPerson(){const {lead:l,quality:q}=current;$('personName').textContent=[l.first_name,l.last_name].join(' ');$('personRole').textContent=[l.current_title,l.company].filter(Boolean).join(' · ');$('personGates').innerHTML=Object.entries(q.gates).map(([f,g])=>`<div class="gate-card"><strong>${esc(labels[f])}</strong> ${badge(g.state)}<p>${esc(g.reason)}</p>${g.evidence?`<small>${esc(g.evidence.source)} · ${esc(g.evidence.observed_at.slice(0,10))}</small><p>${esc(g.evidence.note)}</p>${link(g.evidence.url,'Review original source')}`:''}</div>`).join('');
  const evidence=(l.evidence||[]).filter(e=>e.source_url).slice(-8);$('personSources').innerHTML=(q.warnings.length?`<p>${esc(q.warnings.join(' '))}</p>`:'')+'<h3>Available source material</h3>'+[l.linkedin_url?`<p>${link(l.linkedin_url,'LinkedIn profile')}</p>`:'',...evidence.map(e=>`<p>${link(e.source_url,e.source||'Source')} · ${esc(e.field)}: ${esc(e.value)} <small>${esc(e.source_date||'Publication date not supplied')} · reported, not independently verified</small></p>`)].join('');
  $('personPlans').innerHTML=q.plans.length?q.plans.map(p=>`<p><strong>${esc(p.sponsor)}</strong><br>${esc(p.plan_name)} · ${esc(p.plan_year)}<br>Plan assets: ${dollars(p.net_assets)} · Accounts: ${num(p.participants_with_balances)}<br>Average per account: ${dollars(p.average_account_balance)} · Separated participants with future benefits: ${p.separated_future_benefits==null?'Unknown':num(p.separated_future_benefits)}<small>Employer-level figures; not this person’s balance. ${esc(p.match_basis)}</small>${link(p.source_url,'DOL source')}</p>`).join(''):'<p>No exact employer-plan match found. Absence is not proof that a plan does not exist.</p>';
}
function reviewFields(){const field=$('reviewField').value;Object.keys(labels).forEach(f=>$(f+'Fields').hidden=f!==field||$('verdict').value!=='confirmed');}
$('reviewField').onchange=reviewFields;$('verdict').onchange=reviewFields;
$('reviewForm').onsubmit=async e=>{e.preventDefault();if(!current||$('saveReview').disabled)return;const reviewed=current,version=leadDetailVersion;$('saveReview').disabled=true;$('reviewError').textContent='';try{const field=$('reviewField').value;let value=null;
  if(field==='age')value={min:$('ageMin').value===''?null:Number($('ageMin').value),max:$('ageMax').value===''?null:Number($('ageMax').value)};
  if(field==='residence')value={country:$('residenceConfirmed').checked?'US':'',scope:'residence'};
  if(field==='retirement')value={account_type:$('accountType').value,route:$('distributionRoute').value,assets_confirmed:$('assetsConfirmed').checked,eligible_distribution:$('distributionConfirmed').checked,individual:$('assetsConfirmed').checked,plan_permission:$('planPermission').checked,destination_type:$('destinationType').value,evidence_basis:$('retirementBasis').value,consent_confirmed:$('retirementConsent').checked};
  if(field==='net_worth')value={lower_bound_usd:$('worthLower').value===''?null:Number($('worthLower').value),excludes_home:$('worthHome').checked,net_of_liabilities:$('worthLiabilities').checked,evidence_basis:$('worthBasis').value,consent_confirmed:$('worthConsent').checked};
  if(field==='contact')value={channel:$('contactChannel').value,address:$('contactAddress').value,identity_confirmed:$('contactConfirmed').checked};
  await request('/api/lab/leads/'+encodeURIComponent(reviewed.lead.id)+'/review',{method:'POST',body:JSON.stringify({field,verdict:$('verdict').value,value,source:$('reviewSource').value,url:$('reviewUrl').value,note:$('reviewNote').value,observed_at:$('observedAt').value,identity_signature:reviewed.quality.identity_signature})});if(version===leadDetailVersion){const data=await request('/api/lab/leads/'+encodeURIComponent(reviewed.lead.id));if(version===leadDetailVersion){current=data;renderPerson();await loadActivity(reviewed.lead.id,version,false);$('reviewError').textContent='Review saved.';}}await refresh(false);
  }catch(err){if(version===leadDetailVersion)$('reviewError').textContent=err.message;}finally{if(version===leadDetailVersion)$('saveReview').disabled=false;}};
$('runForm').onsubmit=async e=>{e.preventDefault();$('runButton').disabled=true;try{const result=await request('/api/lab/runs',{method:'POST',body:JSON.stringify({...config(),kind:'discovery',idempotency_key:crypto.randomUUID()})});notice(result.message||'Experiment queued.');await refresh(false);}catch(err){notice(err.message,true);}finally{$('runButton').disabled=false;}};
$('saveSettings').onclick=async()=>{try{await request('/api/lab/settings',{method:'PUT',body:JSON.stringify({configuration:config(),daily_enabled:$('dailyEnabled').checked,daily_hour:Number($('dailyHour').value)})});notice($('dailyEnabled').checked?'Daily experiment saved. The background recovery schedule must be running.':'Settings saved; automatic daily runs are paused.');}catch(e){notice(e.message,true);}};
$('assess').onclick=async()=>{if($('assess').disabled)return;$('assess').disabled=true;try{const result=await request('/api/lab/runs',{method:'POST',body:JSON.stringify({kind:'inventory',idempotency_key:crypto.randomUUID()})});notice(result.message);await refresh(false);}catch(e){notice(e.message,true);}finally{$('assess').disabled=false;}};
$('refresh').onclick=()=>refresh();$('qualityFilter').onchange=()=>{offset=0;loadLeads().catch(e=>notice(e.message,true));};let searchTimer;$('search').oninput=()=>{offset=0;leadLoadVersion++;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{offset=0;loadLeads().catch(e=>notice(e.message,true));},300);};$('previous').onclick=()=>{offset=Math.max(0,offset-50);loadLeads().catch(e=>notice(e.message,true));};$('next').onclick=()=>{offset+=50;loadLeads().catch(e=>notice(e.message,true));};
$('export').onclick=async()=>{if(!selected.size)return notice('Select one or more research records to export.',true);try{const blob=await request('/api/lab/export',{method:'POST',body:JSON.stringify({ids:[...selected]})});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prospectpilot-research.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Research export prepared. Excluded records were omitted.');}catch(e){notice(e.message,true);}};
$('importOpen').onclick=()=>{$('importError').textContent='';$('importDialog').showModal();};$('importForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const file=$('csvFile').files[0];if(!file||file.size>4000000)throw Error('Choose a CSV smaller than 4 MB.');const result=await request('/api/lab/import',{method:'POST',body:JSON.stringify({csv:await file.text(),source:$('importSource').value})});$('importDialog').close();notice(result.replayed?'This exact file was already imported.':`Imported ${result.result.added} new people; ${result.result.duplicates} duplicates, ${result.result.rejected} rejected, ${result.result.ambiguous} ambiguous matches. Claims remain unverified.`);await refresh(false);}catch(err){$('importError').textContent=err.message;}finally{button.disabled=false;}};
$('costOpen').onclick=()=>{if(!runs.length)return notice('Create an experiment or import first, then record its costs.',true);$('costRun').innerHTML=runs.map(r=>`<option value="${esc(r.id)}">${esc(title(r.kind)+' · '+new Date(r.created_at).toLocaleString())}</option>`).join('');$('costError').textContent='';$('costDialog').showModal();};$('costForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await request('/api/lab/costs',{method:'POST',body:JSON.stringify({run_id:$('costRun').value,category:$('costCategory').value,amount_micros:Math.round(Number($('costAmount').value)*1000000),note:$('costNote').value,idempotency_key:crypto.randomUUID()})});$('costDialog').close();await refresh();}catch(err){$('costError').textContent=err.message;}finally{e.submitter.disabled=false;}};
async function openRun(id){const version=++runDetailVersion;$('runDetails').textContent='Loading source results…';if(!$('runDialog').open)$('runDialog').showModal();try{const d=await request('/api/lab/runs/'+encodeURIComponent(id));if(version!==runDetailVersion)return;$('runDetails').innerHTML=`<p>${badge(d.run.status)} · ${esc(new Date(d.run.created_at).toLocaleString())}</p>`+d.tasks.map(t=>`<div class="source-card"><h3>${esc(title(t.source))} · ${esc(t.payload.company||'Saved lead assessment')}</h3>${badge(t.status)}<p>${t.source==='inventory'?(Number.isInteger(t.result?.assessed)?`${num(t.result.assessed)} assessed · ${num(t.result.failed)} failed · ${num(t.result.skipped)} skipped · ${num(t.result.remaining)} not attempted`:'Assessment counts were not recorded for this run.'):`${num(t.result?.added)} new · ${num(t.result?.duplicates)} existing · ${num(t.result?.rejected)} rejected · ${num(t.result?.ambiguous)} ambiguous`}</p><p>${esc((t.result?.errors||[]).join(' '))}</p>${(t.result?.documents||[]).slice(0,8).map(doc=>`<p>${link(doc.url||doc.source_url,'Original source')} <small>${esc(doc.scope||'')} · ${esc(doc.source_date||'date unknown')}</small></p>`).join('')}</div>`).join('')+`<h3>Recorded costs</h3>`+(d.costs.length?d.costs.map(c=>`<p>${esc(title(c.category))}: ${dollars(Number(c.amount_micros)/1000000)} · ${esc(c.basis)}<small>${esc(c.note)}</small></p>`).join(''):'<p>No costs recorded. This does not mean total operating cost is zero.</p>');}catch(e){if(version!==runDetailVersion)return;$('runDetails').innerHTML='<p role="alert">'+esc(e.message)+'</p>'+sourceIssues(runs.find(r=>r.id===id)||{})+'<p>Close this window and select Details to retry.</p>';}}
$('detail').addEventListener('close',()=>{leadDetailVersion++;current=null;$('saveReview').disabled=true;});
$('runDialog').addEventListener('close',()=>{runDetailVersion++;});
document.querySelectorAll('[data-close]').forEach(e=>e.onclick=()=>$(e.dataset.close).close());
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(pollTimer);}else refresh(false);});
async function init(){try{const [me,settings,sources]=await Promise.all([request('/api/me'),request('/api/lab/settings'),request('/api/lab/sources')]);$('account').textContent=me.name||me.email;readSettings(settings);sourceReadiness=sources.readiness;const searchOption=document.querySelector('input[name="source"][value="web_search"]');searchOption.disabled=!sourceReadiness.web_search;if(searchOption.disabled)searchOption.checked=false;$('searchReadiness').textContent=sources.readiness.web_search?'Licensed search: '+(Number(sources.readiness.web_search_query_cost_micros)/1000000).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6})+' per query, at most one query per employer. The daily budget is enforced before each request.':'Licensed web search is unavailable and has been deselected. Free company research and authorized CSV imports remain available.';$('sourceCatalog').innerHTML=sources.sources.map(s=>`<div class="source-card"><h3>${esc(s.name)} ${badge(s.mode)}</h3><p>${esc(s.supports)}</p><p>${esc(s.limit)}</p>${s.url?link(s.url,'Source information'):''}</div>`).join('');await refresh();}catch(e){notice(e.message,true);}}
async function loadActivity(id,version,reset=true){try{const data=await request('/api/lab/leads/'+encodeURIComponent(id)+'/activity');if(version!==leadDetailVersion)return;currentWorkflow=data;$('activityForm').hidden=false;if(reset)prepareActivity();else renderConversation();}catch(e){if(version===leadDetailVersion){$('activityForm').hidden=true;$('conversationBrief').textContent='The activity record could not load. Close and reopen to retry. '+e.message;}}}
let workOffset=0,workTotal=0,workRequest=0,currentWorkflow=null,activityKey='',activitySaving=false;
const workSelected=new Set();
const when=value=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'';
const emptyMessages={today:['Your next actions will appear here.','Import an existing provider CSV or discover people at named employers. Each prospect will have a specific evidence task.'],due:['You’re caught up on due follow-ups.','Scheduled follow-ups return here when their saved time arrives.'],ready:['No prospects are ready for an initial conversation yet.','Review age, US residence, and contact ownership first. Missing retirement and financial evidence remains a conversation topic, not a verified claim.'],review:['No evidence reviews in this view.','Try another worklist or import research candidates.'],enrich:['No missing-contact records in this view.','Contact details that are present but unverified appear under Evidence to review.'],scheduled:['No follow-ups scheduled.','Open a prospect, record the outcome, and choose a next follow-up time.'],meetings:['No meetings saved yet.','Choose Meeting booked on a prospect and record the agreed time.'],closed:['No closed or excluded records.','Contact restrictions and reviewed disqualifications remove records from active work.'],all:['No prospects found.','Import a CSV or change your search.']};
function selectionLabel(){$('workSelection').textContent=`${workSelected.size} selected`;$('enrichExport').disabled=!workSelected.size;}
async function loadWorklist(){
  const serial=++workRequest;const data=await request('/api/lab/worklist?'+new URLSearchParams({view:$('workView').value,search:$('workSearch').value,offset:workOffset,limit:24}));if(serial!==workRequest)return;
  if(workOffset>0&&workOffset>=data.total){workOffset=0;return loadWorklist();}
  workTotal=data.total;$('workDue').textContent=num(data.counts.due);$('workReady').textContent=num(data.counts.ready);$('workConversations').textContent=num(data.activity.conversations);$('workMeetings').textContent=num(data.activity.meetings);
  const [emptyTitle,emptyBody]=emptyMessages[$('workView').value];
  $('workList').innerHTML=data.items.length?data.items.map(({lead:l,quality:q,action:a})=>`<article class="work-card"><label class="select-lead"><input type="checkbox" data-work-select="${esc(l.id)}" aria-label="Select ${esc(l.first_name)} ${esc(l.last_name)} for enrichment" ${workSelected.has(l.id)?'checked':''} ${a.bucket==='closed'?'disabled':''}></label><div><button class="person-button" data-work-open="${esc(l.id)}">${esc(l.first_name)} ${esc(l.last_name)}</button><p class="muted">${esc(l.current_title||'Title unknown')} · ${esc(l.company||'Employer unknown')}</p>${l.location?`<p class="muted">${esc(l.location)}</p>`:''}${badge(q.status)} <span class="muted">${Object.values(q.gates).filter(g=>g.state==='confirmed').length}/5 criteria reviewed</span></div><div class="work-reason"><p class="next-step">${esc(a.label)}</p><p class="muted">${esc(a.reason)}</p>${a.due_at?`<p class="due-label">${esc(when(a.due_at))}</p>`:''}${l.notes?`<p class="muted">Last note: ${esc(l.notes.split('\n').filter(Boolean).at(-1)?.slice(0,240))}</p>`:''}</div><button class="secondary work-open" data-work-open="${esc(l.id)}">Open brief</button></article>`).join(''):`<div class="work-empty"><h3>${esc($('workSearch').value?'No matching prospects.':emptyTitle)}</h3><p class="muted">${esc($('workSearch').value?'Try a different full name or employer.':emptyBody)}</p></div>`;
  document.querySelectorAll('[data-work-open]').forEach(e=>e.onclick=()=>openLead(e.dataset.workOpen));
  document.querySelectorAll('[data-work-select]').forEach(e=>e.onchange=()=>{e.checked?workSelected.add(e.dataset.workSelect):workSelected.delete(e.dataset.workSelect);selectionLabel();});
  $('workPageInfo').textContent=(data.total?`${num(workOffset+1)}–${num(Math.min(workOffset+24,data.total))} of ${num(data.total)}`:'0 prospects')+(data.truncated?` · Showing a working set of ${num(data.scanned)} / ${num(data.scope_total)}; search to narrow.`:'');
  $('workPrevious').disabled=!workOffset;$('workNext').disabled=workOffset+24>=workTotal;selectionLabel();
}
function renderConversation(){
  const a=currentWorkflow.action,q=current.quality;
  const questions={age:'What is your current age?',residence:'Which state do you currently live in?',retirement:'Do you still have a retirement account from a previous employer, or another retirement account you would like reviewed?',contact:'What is the best way to contact you for an agreed follow-up?',net_worth:'If you want a planning review, would you be comfortable sharing an authorized financial summary?'};
  $('conversationBrief').innerHTML=`<p><strong>${esc(a.label)}</strong></p><p>${esc(a.reason)}</p>${a.due_at?`<p>Saved time: <strong>${esc(when(a.due_at))}</strong></p>`:''}<p>${q.status==='verified'?'All five criteria have reviewed evidence. Ask about goals and whether the person wants help; qualification is not a recommendation to transfer assets.':'Still to establish: '+esc(q.gaps.map(k=>labels[k]).join(' · '))+'.'}</p>`+(a.bucket==='closed'?'':`<details><summary>Questions for an appropriate conversation</summary><ul>${(q.gaps.length?q.gaps.map(g=>questions[g]):['What would you like to improve about your current retirement plan?','Would a 15-minute introduction be useful?']).map(v=>`<li>${esc(v)}</li>`).join('')}</ul><p>Answers do not verify a criterion until its evidence review is saved below.</p></details>`);
  $('contactActions').replaceChildren();const c=a.contact;
  if(c){const anchor=document.createElement('a');anchor.className='contact-link';anchor.textContent=c.channel==='phone'?`Call ${c.address}`:c.channel==='email'?`Email ${c.address}`:'Open reviewed LinkedIn profile';anchor.href=c.channel==='phone'?'tel:'+c.address:c.channel==='email'?'mailto:'+encodeURIComponent(c.address):safeURL(c.address);if(c.channel==='linkedin'){anchor.target='_blank';anchor.rel='noopener noreferrer';}$('contactActions').append(anchor);}else $('contactActions').textContent='No reviewed contact shortcut available. Review the contact evidence below.';
  $('activityHistory').innerHTML=(current.lead.notes?`<p class="existing-notes">${esc(current.lead.notes)}</p>`:'')+(currentWorkflow.activities.length?currentWorkflow.activities.map(a=>`<div class="activity-entry"><strong>${esc(title(a.outcome))}</strong> · ${esc(when(a.created_at))}<p>${esc(a.note)}</p>${a.next_at?`<small>Next: ${esc(when(a.next_at))}</small>`:''}</div>`).join(''):'<p>No outcomes recorded yet.</p>');
}
function activityFields(){const outcome=$('activityOutcome').value,closed=['not_interested','do_not_contact','reopen'].includes(outcome);$('nextAtLabel').hidden=closed;$('activityNext').required=['follow_up','meeting_booked'].includes(outcome);$('activityNext').disabled=closed;}
function prepareActivity(){renderConversation();$('activityForm').reset();$('activityError').textContent='';activityKey=crypto.randomUUID();const next=new Date();next.setDate(next.getDate()+1);next.setHours(9,0,0,0);const local=new Date(next.getTime()-next.getTimezoneOffset()*60000).toISOString().slice(0,16);$('activityNext').value=local;activityFields();}
$('activityOutcome').onchange=activityFields;
$('activityForm').onsubmit=async e=>{e.preventDefault();if(!current||!currentWorkflow||activitySaving)return;const version=leadDetailVersion;activitySaving=true;$('saveActivity').disabled=true;$('activityError').textContent='';try{
  const result=await request('/api/lab/leads/'+encodeURIComponent(current.lead.id)+'/activity',{method:'POST',body:JSON.stringify({outcome:$('activityOutcome').value,note:$('activityNote').value,next_at:$('activityNext').disabled||!$('activityNext').value?null:new Date($('activityNext').value).toISOString(),signature:currentWorkflow.action.signature,idempotency_key:activityKey})});
  if(result.saved){if(version===leadDetailVersion)$('detail').close();notice('Outcome saved. Your follow-up and worklist are updated.');await refresh(false);}
}catch(err){if(version===leadDetailVersion)$('activityError').textContent=err.message;else notice(err.message,true);}finally{activitySaving=false;$('saveActivity').disabled=false;}};
$('quickImport').onclick=()=>$('importOpen').click();
$('findProspects').onclick=()=>{$('researchTools').open=true;$('runForm').scrollIntoView({behavior:'smooth',block:'start'});$('employers').focus({preventScroll:true});};
$('workView').onchange=()=>{workOffset=0;loadWorklist().catch(e=>notice(e.message,true));};let workSearchTimer;
$('workSearch').oninput=()=>{workRequest++;clearTimeout(workSearchTimer);workSearchTimer=setTimeout(()=>{workOffset=0;loadWorklist().catch(e=>notice(e.message,true));},250);};
$('workPrevious').onclick=()=>{workOffset=Math.max(0,workOffset-24);loadWorklist().catch(e=>notice(e.message,true));};$('workNext').onclick=()=>{workOffset+=24;loadWorklist().catch(e=>notice(e.message,true));};
$('enrichExport').onclick=async()=>{if(!workSelected.size)return;try{const blob=await request('/api/lab/enrichment-export',{method:'POST',body:JSON.stringify({ids:[...workSelected]})});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prospectpilot-enrichment.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Provider matching CSV prepared. Import the enriched results to merge them into your existing prospects.');}catch(e){notice(e.message,true);}};
init();
