const $=id=>document.getElementById(id);
const labels={age:'Age 45–73',residence:'US residence',retirement:'Transfer eligibility',contact:'Contact route',net_worth:'Net worth ≥ $250K, home excluded'};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=value=>String(value||'').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const num=value=>Number(value||0).toLocaleString();
const dollars=value=>value==null?'—':Number(value).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const safeURL=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}};
const link=(url,text)=>safeURL(url)?`<a href="${esc(safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(text)}</a>`:esc(text);
const badge=(value)=>`<span class="badge ${esc(value)}">${esc(title(value))}</span>`;
let offset=0,total=0,leads=[],runs=[],current=null,busy=false,pollTimer=null,sourceReadiness=null;
const selected=new Set();
async function request(path,options={}) {
  const response=await fetch(path,{...options,headers:{'content-type':'application/json',...options.headers}});
  if(response.status===401){location.href='/login';throw Error('Please sign in.');}
  if(!response.ok){let data;try{data=await response.json();}catch{}throw Error(data?.detail||`Request failed (${response.status}).`);}
  return response.headers.get('content-type')?.includes('text/csv')?response.blob():response.json();
}
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function config(){return {employers:$('employers').value.split('\n').map(s=>s.trim()).filter(Boolean),websites:$('websites').value.split('\n').map(s=>s.trim()),states:$('states').value.split(/[,;\s]+/).filter(Boolean),sources:[...document.querySelectorAll('input[name="source"]:checked')].map(e=>e.value),max_companies:Number($('maxCompanies').value),daily_budget_micros:Math.round(Number($('budget').value)*1000000)};}
function readSettings(value){const c=value.configuration||{};$('employers').value=(c.employers||[]).join('\n');$('websites').value=(c.websites||[]).join('\n');$('states').value=(c.states||[]).join(', ');$('maxCompanies').value=c.max_companies||10;$('budget').value=Number(value.daily_budget_micros||0)/1000000;$('dailyEnabled').checked=value.daily_enabled===true;$('dailyHour').value=value.daily_hour??13;document.querySelectorAll('input[name="source"]').forEach(e=>{e.checked=(c.sources||['public_web','sec','warn']).includes(e.value);});}
function renderSummary(s){
  $('metricSourced').textContent=num(s.totals.new_sourced);$('metricVerified').textContent=num(s.totals.newly_verified);$('metricCpl').textContent=dollars(s.totals.cost_per_verified);$('metricDaily').textContent=s.totals.verified_per_calendar_day.toFixed(1);$('costBasis').textContent=`${dollars(s.totals.cost_usd)} recorded · other costs may be unrecorded`;
  const max=Math.max(1,...s.daily.flatMap(d=>[d.new_sourced,d.newly_verified]));$('dailyChart').replaceChildren();
  for(const d of s.daily){const column=document.createElement('div');column.className='chart-column';column.title=`${d.day}: ${d.new_sourced} sourced, ${d.newly_verified} verified, ${d.imported} imported`;const bars=document.createElement('div');bars.className='bars';for(const key of ['new_sourced','newly_verified']){const bar=document.createElement('div');bar.className=key==='newly_verified'?'bar verified':'bar';bar.style.height=`${Math.max(1,Number(d[key])/max*100)}%`;bars.append(bar);}const date=document.createElement('span');date.textContent=d.day.slice(5);column.append(bars,date);$('dailyChart').append(column);}
  $('inventory').innerHTML=s.inventory.map(i=>`<span class="badge ${esc(i.status)}">${esc(title(i.status))} · ${num(i.n)}</span>`).join('')||'<span class="muted">Your research inventory is empty.</span>';
  $('catalog').textContent=s.catalog.plans?`${num(s.catalog.plans)} distinct employer plans · ${num(s.catalog.filings)} filing records · latest plan year ${s.catalog.latest_plan_year}. Catalog loaded ${new Date(s.catalog.imported_at).toLocaleDateString()}; filing dates are recorded separately. These are employer records, not individual leads.`:'Employer-plan catalog not loaded yet. Start with named employers or import your existing leads.';
  $('sourceMetrics').innerHTML=s.sources.length?'<div class="table-wrap"><table><thead><tr><th>Source</th><th>Acquired</th><th>Qualified</th><th>Yield</th><th>Attempts / gaps</th><th>Reserved provider cost</th><th>Provider cost / qualified</th></tr></thead><tbody>'+s.sources.map(row=>`<tr><td>${esc(title(row.source))}</td><td>${num(row.acquired)}</td><td>${num(row.qualified)}</td><td>${row.qualification_rate==null?"—":(row.qualification_rate*100).toFixed(1)+"%"}</td><td>${num(row.attempts)} / ${num(row.gaps)}</td><td>${dollars(row.cost_micros==null?null:Number(row.cost_micros)/1000000)}</td><td>${dollars(row.reserved_cost_per_qualified)}</td></tr>`).join('')+'</tbody></table></div>':'<p class="empty">Run an experiment to compare source yield and cost.</p>';
}
function renderLeads(data){leads=data.leads;total=data.total;
  $('leadTable').innerHTML=leads.length?'<table><thead><tr><th><input id="selectPage" type="checkbox" aria-label="Select this page"></th><th>Prospect</th><th>Quality</th><th>Evidence</th><th>Criteria: age / US / assets / contact / net worth</th><th>Next review</th></tr></thead><tbody>'+leads.map(({lead:l,quality:q})=>`<tr><td><input type="checkbox" data-select="${esc(l.id)}" aria-label="Select ${esc(l.first_name)} ${esc(l.last_name)}" ${selected.has(l.id)?'checked':''}></td><td><button class="person-button" data-lead="${esc(l.id)}">${esc(l.first_name)} ${esc(l.last_name)}</button><small>${esc(l.current_title||'Title unknown')} · ${esc(l.company||'Employer unknown')}</small></td><td>${badge(q.status)}</td><td>${num(q.score)} / 100</td><td><div class="criteria">${Object.entries(q.gates).map(([key,g])=>`<span class="criterion ${esc(g.state)}" title="${esc(labels[key]+': '+g.reason)}">${g.state==='confirmed'?'✓':g.state==='candidate'?'~':g.state==='failed'?'×':'?'}</span>`).join('')}</div></td><td>${esc(labels[q.gaps[0]]||'Complete')}</td></tr>`).join('')+'</tbody></table>':'<p class="empty">No records in this view. Import candidates or run discovery to begin.</p>';
  document.querySelectorAll('[data-lead]').forEach(e=>e.onclick=()=>openLead(e.dataset.lead));document.querySelectorAll('[data-select]').forEach(e=>e.onchange=()=>{e.checked?selected.add(e.dataset.select):selected.delete(e.dataset.select);});
  if($('selectPage'))$('selectPage').onchange=e=>{leads.forEach(({lead})=>e.target.checked?selected.add(lead.id):selected.delete(lead.id));renderLeads(data);};
  $('pageInfo').textContent=total?`${num(offset+1)}–${num(Math.min(offset+50,total))} of ${num(total)} · assessed filter, live evidence`:'0 records';$('previous').disabled=offset===0;$('next').disabled=offset+50>=total;
}
async function loadLeads(){const query=new URLSearchParams({offset,limit:50,status:$('qualityFilter').value,search:$('search').value});renderLeads(await request('/api/lab/leads?'+query));}
function sourceIssues(run){return (run.source_results||[]).filter(t=>(t.errors||[]).length).map(t=>`<p class="muted"><strong>${esc(title(t.source))}${t.company?' · '+esc(t.company):''}:</strong> ${esc(t.errors.join(' '))}</p>`).join('');}
function renderRuns(data){runs=data.runs;$('runs').innerHTML=runs.length?runs.map(r=>`<div class="run"><div><strong>${esc(title(r.kind))}</strong> ${badge(r.status)}<small>${esc(new Date(r.created_at).toLocaleString())} · ${num(r.finished_tasks)}/${num(r.tasks)} checks · ${num(r.new_people)} new people</small>${r.kind==='discovery'&&!Number(r.new_people)&&!['queued','running'].includes(r.status)?'<p>No people were added. Review the source results below; this does not establish that no prospects exist.</p>':''}${sourceIssues(r)}</div><button class="secondary" data-run="${esc(r.id)}">Details</button></div>`).join(''):'<p class="empty">No experiments yet.</p>';
  document.querySelectorAll('[data-run]').forEach(e=>e.onclick=()=>openRun(e.dataset.run));

}
async function refresh(showNotice=true){
  if(busy)return;busy=true;clearTimeout(pollTimer);$('refresh').disabled=true;
  const sections=[['Summary',()=>request('/api/lab/summary').then(renderSummary)],['Run history',()=>request('/api/lab/runs').then(renderRuns)],['Lead results',loadLeads]];
  try{
    const results=await Promise.allSettled(sections.map(([,load])=>load()));
    const failures=results.flatMap((r,i)=>r.status==='rejected'?[sections[i][0]+': '+r.reason.message]:[]);
    if(failures.length)notice('Some sections could not refresh. Successfully loaded results are shown. '+failures.join(' '),true);
    else if(showNotice)notice('Results updated. Verified counts require reviewed evidence for all five criteria.');
  }finally{
    busy=false;$('refresh').disabled=false;
    if(!document.hidden&&runs.some(r=>['queued','running'].includes(r.status)))pollTimer=setTimeout(()=>refresh(false),8000);
  }
}
async function openLead(id){try{current=await request('/api/lab/leads/'+encodeURIComponent(id));renderPerson();$('reviewForm').reset();$('observedAt').value=new Date().toISOString().slice(0,10);$('observedAt').max=new Date().toISOString().slice(0,10);$('reviewError').textContent='';reviewFields();$('detail').showModal();}catch(e){notice(e.message,true);}}
function renderPerson(){const {lead:l,quality:q}=current;$('personName').textContent=[l.first_name,l.last_name].join(' ');$('personRole').textContent=[l.current_title,l.company].filter(Boolean).join(' · ');$('personGates').innerHTML=Object.entries(q.gates).map(([f,g])=>`<div class="gate-card"><strong>${esc(labels[f])}</strong> ${badge(g.state)}<p>${esc(g.reason)}</p>${g.evidence?`<small>${esc(g.evidence.source)} · ${esc(g.evidence.observed_at.slice(0,10))}</small><p>${esc(g.evidence.note)}</p>${link(g.evidence.url,'Review original source')}`:''}</div>`).join('');
  const evidence=(l.evidence||[]).filter(e=>e.source_url).slice(-8);$('personSources').innerHTML=(q.warnings.length?`<p>${esc(q.warnings.join(' '))}</p>`:'')+'<h3>Available source material</h3>'+[l.linkedin_url?`<p>${link(l.linkedin_url,'LinkedIn profile')}</p>`:'',...evidence.map(e=>`<p>${link(e.source_url,e.source||'Source')} · ${esc(e.field)}: ${esc(e.value)} <small>${esc(e.source_date||'Publication date not supplied')} · reported, not independently verified</small></p>`)].join('');
  $('personPlans').innerHTML=q.plans.length?q.plans.map(p=>`<p><strong>${esc(p.sponsor)}</strong><br>${esc(p.plan_name)} · ${esc(p.plan_year)}<br>Plan assets: ${dollars(p.net_assets)} · Accounts: ${num(p.participants_with_balances)}<br>Average per account: ${dollars(p.average_account_balance)} · Separated participants with future benefits: ${p.separated_future_benefits==null?'Unknown':num(p.separated_future_benefits)}<small>Employer-level figures; not this person’s balance. ${esc(p.match_basis)}</small>${link(p.source_url,'DOL source')}</p>`).join(''):'<p>No exact employer-plan match found. Absence is not proof that a plan does not exist.</p>';
}
function reviewFields(){const field=$('reviewField').value;Object.keys(labels).forEach(f=>$(f+'Fields').hidden=f!==field||$('verdict').value!=='confirmed');}
$('reviewField').onchange=reviewFields;$('verdict').onchange=reviewFields;
$('reviewForm').onsubmit=async e=>{e.preventDefault();if(!current)return;$('saveReview').disabled=true;$('reviewError').textContent='';try{const field=$('reviewField').value;let value=null;
  if(field==='age')value={min:$('ageMin').value===''?null:Number($('ageMin').value),max:$('ageMax').value===''?null:Number($('ageMax').value)};
  if(field==='residence')value={country:$('residenceConfirmed').checked?'US':'',scope:'residence'};
  if(field==='retirement')value={account_type:$('accountType').value,route:$('distributionRoute').value,assets_confirmed:$('assetsConfirmed').checked,eligible_distribution:$('distributionConfirmed').checked,individual:$('assetsConfirmed').checked,plan_permission:$('planPermission').checked,destination_type:$('destinationType').value,evidence_basis:$('retirementBasis').value,consent_confirmed:$('retirementConsent').checked};
  if(field==='net_worth')value={lower_bound_usd:$('worthLower').value===''?null:Number($('worthLower').value),excludes_home:$('worthHome').checked,net_of_liabilities:$('worthLiabilities').checked,evidence_basis:$('worthBasis').value,consent_confirmed:$('worthConsent').checked};
  if(field==='contact')value={channel:$('contactChannel').value,address:$('contactAddress').value,identity_confirmed:$('contactConfirmed').checked};
  await request('/api/lab/leads/'+encodeURIComponent(current.lead.id)+'/review',{method:'POST',body:JSON.stringify({field,verdict:$('verdict').value,value,source:$('reviewSource').value,url:$('reviewUrl').value,note:$('reviewNote').value,observed_at:$('observedAt').value,identity_signature:current.quality.identity_signature})});current=await request('/api/lab/leads/'+encodeURIComponent(current.lead.id));renderPerson();$('reviewError').textContent='Review saved.';await refresh(false);
  }catch(err){$('reviewError').textContent=err.message;}finally{$('saveReview').disabled=false;}};
$('runForm').onsubmit=async e=>{e.preventDefault();$('runButton').disabled=true;try{const result=await request('/api/lab/runs',{method:'POST',body:JSON.stringify({...config(),kind:'discovery',idempotency_key:crypto.randomUUID()})});notice(result.message||'Experiment queued.');await refresh(false);}catch(err){notice(err.message,true);}finally{$('runButton').disabled=false;}};
$('saveSettings').onclick=async()=>{try{await request('/api/lab/settings',{method:'PUT',body:JSON.stringify({configuration:config(),daily_enabled:$('dailyEnabled').checked,daily_hour:Number($('dailyHour').value)})});notice($('dailyEnabled').checked?'Daily experiment saved. The background recovery schedule must be running.':'Settings saved; automatic daily runs are paused.');}catch(e){notice(e.message,true);}};
$('assess').onclick=async()=>{try{const result=await request('/api/lab/runs',{method:'POST',body:JSON.stringify({kind:'inventory',idempotency_key:crypto.randomUUID()})});notice(result.message);await refresh(false);}catch(e){notice(e.message,true);}};
$('refresh').onclick=()=>refresh();$('qualityFilter').onchange=()=>{offset=0;loadLeads().catch(e=>notice(e.message,true));};let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{offset=0;loadLeads().catch(e=>notice(e.message,true));},300);};$('previous').onclick=()=>{offset=Math.max(0,offset-50);loadLeads().catch(e=>notice(e.message,true));};$('next').onclick=()=>{offset+=50;loadLeads().catch(e=>notice(e.message,true));};
$('export').onclick=async()=>{if(!selected.size)return notice('Select one or more research records to export.',true);try{const blob=await request('/api/lab/export',{method:'POST',body:JSON.stringify({ids:[...selected]})});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prospectpilot-research.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Research export prepared. Excluded records were omitted.');}catch(e){notice(e.message,true);}};
$('importOpen').onclick=()=>{$('importError').textContent='';$('importDialog').showModal();};$('importForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const file=$('csvFile').files[0];if(!file||file.size>4000000)throw Error('Choose a CSV smaller than 4 MB.');const result=await request('/api/lab/import',{method:'POST',body:JSON.stringify({csv:await file.text(),source:$('importSource').value})});$('importDialog').close();notice(result.replayed?'This exact file was already imported.':`Imported ${result.result.added} new people; ${result.result.duplicates} duplicates, ${result.result.rejected} rejected, ${result.result.ambiguous} ambiguous matches. Claims remain unverified.`);await refresh(false);}catch(err){$('importError').textContent=err.message;}finally{button.disabled=false;}};
$('costOpen').onclick=()=>{if(!runs.length)return notice('Create an experiment or import first, then record its costs.',true);$('costRun').innerHTML=runs.map(r=>`<option value="${esc(r.id)}">${esc(title(r.kind)+' · '+new Date(r.created_at).toLocaleString())}</option>`).join('');$('costError').textContent='';$('costDialog').showModal();};$('costForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await request('/api/lab/costs',{method:'POST',body:JSON.stringify({run_id:$('costRun').value,category:$('costCategory').value,amount_micros:Math.round(Number($('costAmount').value)*1000000),note:$('costNote').value,idempotency_key:crypto.randomUUID()})});$('costDialog').close();await refresh();}catch(err){$('costError').textContent=err.message;}finally{e.submitter.disabled=false;}};
async function openRun(id){$('runDetails').textContent='Loading source results…';$('runDialog').showModal();try{const d=await request('/api/lab/runs/'+encodeURIComponent(id));$('runDetails').innerHTML=`<p>${badge(d.run.status)} · ${esc(new Date(d.run.created_at).toLocaleString())}</p>`+d.tasks.map(t=>`<div class="source-card"><h3>${esc(title(t.source))} · ${esc(t.payload.company||'Saved lead assessment')}</h3>${badge(t.status)}<p>${num(t.result?.added)} new · ${num(t.result?.duplicates)} existing · ${num(t.result?.rejected)} rejected · ${num(t.result?.ambiguous)} ambiguous</p><p>${esc((t.result?.errors||[]).join(' '))}</p>${(t.result?.documents||[]).slice(0,8).map(doc=>`<p>${link(doc.url||doc.source_url,'Original source')} <small>${esc(doc.scope||'')} · ${esc(doc.source_date||'date unknown')}</small></p>`).join('')}</div>`).join('')+`<h3>Recorded costs</h3>`+(d.costs.length?d.costs.map(c=>`<p>${esc(title(c.category))}: ${dollars(Number(c.amount_micros)/1000000)} · ${esc(c.basis)}<small>${esc(c.note)}</small></p>`).join(''):'<p>No costs recorded. This does not mean total operating cost is zero.</p>');}catch(e){$('runDetails').innerHTML='<p role="alert">'+esc(e.message)+'</p>'+sourceIssues(runs.find(r=>r.id===id)||{})+'<p>Close this window and select Details to retry.</p>';}}
document.querySelectorAll('[data-close]').forEach(e=>e.onclick=()=>$(e.dataset.close).close());
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(pollTimer);}else refresh(false);});
async function init(){try{const [me,settings,sources]=await Promise.all([request('/api/me'),request('/api/lab/settings'),request('/api/lab/sources')]);$('account').textContent=me.name||me.email;readSettings(settings);sourceReadiness=sources.readiness;const searchOption=document.querySelector('input[name="source"][value="web_search"]');searchOption.disabled=!sourceReadiness.web_search;if(searchOption.disabled)searchOption.checked=false;$('searchReadiness').textContent=sources.readiness.web_search?'Licensed search: '+(Number(sources.readiness.web_search_query_cost_micros)/1000000).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6})+' per query, at most one query per employer. The daily budget is enforced before each request.':'Licensed web search is unavailable and has been deselected. Free company research and authorized CSV imports remain available.';$('sourceCatalog').innerHTML=sources.sources.map(s=>`<div class="source-card"><h3>${esc(s.name)} ${badge(s.mode)}</h3><p>${esc(s.supports)}</p><p>${esc(s.limit)}</p>${s.url?link(s.url,'Source information'):''}</div>`).join('');await refresh();}catch(e){notice(e.message,true);}}
init();
