import {initProviderUI} from './prospect-jobs-client.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let offset=0,contacts=[],lists=[],searches=[],loadVersion=0;const selected=new Set();
const notice=(message,error=false)=>{$('notice').textContent=message;$('notice').classList.toggle('error',error);};
async function api(path,body,method=body?'POST':'GET'){const r=await fetch('/api/prospect/'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(r.status===401){location.href='/login';throw Error('Sign in to continue.');}if(!r.ok){let data;try{data=await r.json();}catch{}throw Error(data?.detail||'Request failed.');}return r.headers.get('Content-Type')?.includes('text/csv')?r.blob():r.json();}
const filters=()=>({...Object.fromEntries(new FormData($('filters'))),list_id:$('listFilter').value});
function selection(){ $('selectedCount').textContent=selected.size+' selected';for(const id of ['export','addListOpen','removeList'])$(id).disabled=!selected.size;}
async function load(){const version=++loadVersion;try{const data=await api('contacts?'+new URLSearchParams({...filters(),offset,limit:50,compact:'true'}));if(version!==loadVersion)return;contacts=data.contacts;$('total').textContent=data.total.toLocaleString()+' contacts in your directory';$('resultTitle').textContent=lists.find(l=>l.id===$('listFilter').value)?.name||'All contacts';$('removeList').hidden=!$('listFilter').value;
 $('table').innerHTML=contacts.length?'<table><thead><tr><th><input id="selectPage" type="checkbox" aria-label="Select this page"></th><th>Contact</th><th>Company</th><th>Email</th><th>Phone</th><th>Location</th></tr></thead><tbody>'+contacts.map(c=>`<tr><td><input type="checkbox" data-id="${esc(c.id)}" aria-label="Select ${esc(c.first_name+' '+c.last_name)}" ${selected.has(c.id)?'checked':''}></td><td><button class="text-button contact-name" data-contact="${esc(c.id)}">${esc(c.first_name+' '+c.last_name)}</button><small>${esc(c.title||'Title not provided')}</small>${c.linkedin_url?`<a href="${esc(c.linkedin_url)}" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>`:''}${c.suppressed?'<span class="badge suppressed">Suppressed</span>':''}</td><td>${esc(c.company||'—')}<small>${esc(c.industry)}</small></td><td>${esc(c.email||'No email')}<br><span class="badge ${esc(c.email_status)}">${esc(c.email_status)}</span></td><td>${esc(c.phone||'No phone')}<br><span class="badge">${esc(c.phone_status)}</span></td><td>${esc([c.city,c.state,c.country].filter(Boolean).join(', ')||'—')}<small>${esc(c.source)}</small></td></tr>`).join('')+'</tbody></table>':'<div class="empty"><h2>No contacts match this view</h2><p>Import an authorized contact list or adjust your filters to begin.</p></div>';
 document.querySelectorAll('[data-contact]').forEach(el=>el.onclick=()=>showContact(el.dataset.contact));document.querySelectorAll('[data-id]').forEach(e=>e.onchange=()=>{e.checked?selected.add(e.dataset.id):selected.delete(e.dataset.id);selection();});if($('selectPage')){$('selectPage').checked=contacts.every(c=>selected.has(c.id));$('selectPage').onchange=e=>{contacts.forEach(c=>e.target.checked?selected.add(c.id):selected.delete(c.id));document.querySelectorAll('[data-id]').forEach(el=>el.checked=e.target.checked);selection();};}
 $('pageLabel').textContent=data.total?`${offset+1}–${Math.min(offset+50,data.total)} of ${data.total}`:'0 contacts';$('previous').disabled=offset===0;$('next').disabled=offset+50>=data.total;selection();
 }catch(e){if(version===loadVersion)notice(e.message,true);}}
async function loadLists(){lists=(await api('lists')).lists;for(const id of ['listFilter','importList','addList']){const value=$(id).value;$(id).innerHTML=(id==='addList'?'':`<option value="">${id==='listFilter'?'All contacts':'No list'}</option>`)+lists.map(l=>`<option value="${esc(l.id)}">${esc(l.name)} (${l.contacts})</option>`).join('');if([...$(id).options].some(o=>o.value===value))$(id).value=value;}}
async function loadSearches(){
 searches=(await api('saved-searches')).searches;
 $('searches').innerHTML=searches.length?searches.map(s=>`<div class="saved-search"><button class="text-button" data-search="${esc(s.id)}">${esc(s.name)}</button><button class="text-button" data-delete-search="${esc(s.id)}" aria-label="Delete saved search ${esc(s.name)}">Delete</button></div>`).join(''):'<p class="muted">Save filters you use often.</p>';
 document.querySelectorAll('[data-search]').forEach(el=>el.onclick=()=>{const f=searches.find(s=>s.id===el.dataset.search).filters;$('filters').reset();for(const [key,value] of Object.entries(f)){const input=$('filters').elements.namedItem(key);if(input)input.value=value;}$('listFilter').value=f.list_id||'';offset=0;selected.clear();load();});
 document.querySelectorAll('[data-delete-search]').forEach(el=>el.onclick=async()=>{el.disabled=true;try{await api('saved-searches/'+encodeURIComponent(el.dataset.deleteSearch),undefined,'DELETE');await loadSearches();notice('Saved search deleted.');}catch(e){el.disabled=false;notice(e.message,true);}});
}
$('filters').onsubmit=e=>{e.preventDefault();offset=0;selected.clear();load();};$('filters').onreset=()=>setTimeout(()=>{offset=0;selected.clear();load();},0);$('listFilter').onchange=()=>{offset=0;selected.clear();load();};$('previous').onclick=()=>{offset=Math.max(0,offset-50);load();};$('next').onclick=()=>{offset+=50;load();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
for(const [button,dialog] of [['importOpen','importDialog'],['newListOpen','listDialog'],['saveSearchOpen','searchDialog']])$(button).onclick=()=>$(dialog).showModal();
$('addListOpen').onclick=()=>{if(!lists.length)return notice('Create a list first.');$('addDialog').showModal();};
async function submit(event,errorId,operation){event.preventDefault();const b=event.submitter;b.disabled=true;$(errorId).textContent='';try{await operation();}catch(e){$(errorId).textContent=e.message;}finally{b.disabled=false;}}
$('listForm').onsubmit=e=>submit(e,'listError',async()=>{await api('lists',{name:$('listName').value});await loadLists();$('listDialog').close();$('listForm').reset();notice('List created.');});
$('searchForm').onsubmit=e=>submit(e,'searchError',async()=>{await api('saved-searches',{name:$('searchName').value,filters:filters()});await loadSearches();$('searchDialog').close();$('searchForm').reset();notice('Search saved.');});
$('addForm').onsubmit=e=>submit(e,'addError',async()=>{await api('lists/'+encodeURIComponent($('addList').value)+'/members',{ids:[...selected]});await loadLists();$('addDialog').close();notice('Selected contacts added to the list.');});
$('removeList').onclick=async()=>{try{await api('lists/'+encodeURIComponent($('listFilter').value)+'/members',{ids:[...selected]},'DELETE');selected.clear();await loadLists();await load();notice('Contacts removed from this list; they remain in your directory.');}catch(e){notice(e.message,true);}};
let lastImportReport=null,importRevision=0;
const importMessage=r=>(r.preview?'Preview — nothing saved. ':'')+(r.replayed?'This exact import was already processed. ':`${r.added} new · ${r.duplicates} matched · ${r.conflicts} conflicts · ${r.rejected} rejected.`);
function renderImportReport(r,{archived=false}={}){
 if(!archived){lastImportReport=r;$('downloadImportReport').hidden=!r.rows?.length;}
 $(archived?'archivedImportResult':'importResult').textContent=importMessage(r);
 const ignored=r.ignored_columns?.length?`<p><strong>Ignored columns:</strong> ${r.ignored_columns.map(esc).join(', ')}. Imported status claims are never accepted as verification.</p>`:'';
 const rows=r.rows||[];
 $(archived?'archivedImportBody':'importPreview').innerHTML=ignored+(rows.length?'<p class="muted">First 50 rows shown. Download the row report for all results.</p><div class="table-wrap"><table><thead><tr><th>Source line</th><th>Contact</th><th>Result</th><th>Review notes</th></tr></thead><tbody>'+rows.slice(0,50).map(row=>`<tr><td>${row.row}</td><td>${esc(row.name||'—')}</td><td>${esc(row.status)}</td><td>${esc(row.message)}${(row.issues||[]).map(issue=>`<small>${esc(issue.message)}</small>`).join('')}</td></tr>`).join('')+'</tbody></table></div>':(r.errors||[]).map(row=>`<p>Line ${row.row}: ${esc(row.message)}</p>`).join(''));
}
async function importInput(){
 let csv;
 if($('importInputMode').value==='paste')csv=$('csvText').value;
 else{const file=$('csvFile').files[0];if(!file||file.size>4000000)throw Error('Choose a CSV up to 4 MB, or switch to Paste CSV text.');csv=await file.text();}
 if(!csv.trim()||new TextEncoder().encode(csv).length>4000000)throw Error('Provide CSV headers and rows, up to 4 MB.');
 return {csv,format:$('importFormat').value,source:$('source').value,list_id:$('importList').value||undefined,source_url:$('sourceURL').value||undefined,source_observed_at:$('sourceObservedAt').value||undefined};
}
function clearPreview(){importRevision++;lastImportReport=null;$('importPreview').replaceChildren();$('importResult').textContent='';$('downloadImportReport').hidden=true;}
$('importInputMode').onchange=()=>{$('csvFileLabel').hidden=$('importInputMode').value==='paste';$('csvTextLabel').hidden=$('importInputMode').value!=='paste';clearPreview();};
for(const id of ['csvFile','csvText','source','sourceURL','sourceObservedAt','importList','importFormat'])$(id).addEventListener('input',clearPreview);
$('previewImport').onclick=async()=>{const button=$('previewImport'),version=importRevision;button.disabled=true;try{const r=await api('import/preview',await importInput());if(version===importRevision)renderImportReport(r);}catch(e){if(version===importRevision)$('importResult').textContent=e.message;}finally{button.disabled=false;}};
$('importForm').onsubmit=e=>submit(e,'importResult',async()=>{const version=importRevision,r=await api('import',await importInput());await loadLists();offset=0;selected.clear();await load();if(version===importRevision)renderImportReport(r);notice(importMessage(r));});
function downloadCSV(name,rows){const cell=value=>'"'+String(value??'').replace(/^[\s]*[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadReport(report){downloadCSV('prospectpilot-import-report.csv',[['Source line','Contact','Result','Message','Review notes'],...(report.rows||[]).map(row=>[row.row,row.name,row.status,row.message,(row.issues||[]).map(issue=>issue.message).join(' ')])]);}
$('downloadImportReport').onclick=()=>{if(lastImportReport)downloadReport(lastImportReport);};
$('export').onclick=async()=>{try{const blob=await api('export',{ids:[...selected]});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prospectpilot-contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Export ready. Suppressed contacts were omitted.');}catch(e){notice(e.message,true);}};
try{await Promise.all([loadLists(),loadSearches()]);await load();notice('Your contact workspace is ready.');}catch(e){notice(e.message,true);}

initProviderUI({api,selected,filters,getLists:()=>lists,refresh:async()=>{await loadLists();await load();},notice}).catch(e=>notice(e.message,true));

// List management uses the existing owner-scoped API and leaves contacts intact.
const manageButton=document.createElement('button');manageButton.className='secondary';manageButton.textContent='Manage list';$('newListOpen').after(manageButton);
document.body.insertAdjacentHTML('beforeend','<dialog id="manageListDialog"><form id="manageListForm"><div class="dialog-title"><h2>Manage list</h2><button type="button" class="secondary" id="closeManageList">Close</button></div><label>List<select id="managedList" required></select></label><label>List name<input id="manageListName" required maxlength="100"></label><p id="manageListError" role="alert"></p><button type="submit">Save name</button><hr><p>Deleting this list removes its memberships. Contacts stay in your directory. Saved searches using it will search all contacts.</p><button type="button" class="secondary" id="deleteList">Delete list</button></form></dialog>');
const managedName=()=>{$('manageListName').value=lists.find(l=>l.id===$('managedList').value)?.name||'';};
manageButton.onclick=()=>{if(!lists.length)return notice('Create a list first.');$('managedList').innerHTML=lists.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');if($('listFilter').value)$('managedList').value=$('listFilter').value;managedName();$('manageListError').textContent='';$('manageListDialog').showModal();};
$('managedList').onchange=managedName;$('closeManageList').onclick=()=>$('manageListDialog').close();
$('manageListForm').onsubmit=e=>submit(e,'manageListError',async()=>{await api('lists/'+encodeURIComponent($('managedList').value),{name:$('manageListName').value},'PATCH');await loadLists();await load();$('manageListDialog').close();notice('List renamed.');});
$('deleteList').onclick=async()=>{const button=$('deleteList');button.disabled=true;try{const id=$('managedList').value;await api('lists/'+encodeURIComponent(id),undefined,'DELETE');if($('listFilter').value===id){$('listFilter').value='';offset=0;selected.clear();}await Promise.all([loadLists(),loadSearches()]);await load();$('manageListDialog').close();notice('List deleted. Its contacts remain in your directory.');}catch(e){$('manageListError').textContent=e.message;}finally{button.disabled=false;}};


let contactViewVersion=0;
async function showContact(id){
 const version=++contactViewVersion;
  if(!$('contactDialog')){document.body.insertAdjacentHTML('beforeend','<dialog id="contactDialog"><div class="dialog-title"><h2 id="contactTitle">Contact details</h2><button class="secondary" id="closeContact">Close</button></div><div id="contactBody"></div><p id="contactError" role="alert"></p><button id="toggleSuppression"></button></dialog>');$('closeContact').onclick=()=>$('contactDialog').close();$('contactDialog').addEventListener('close',()=>{contactViewVersion++;});}
 $('contactTitle').textContent='Loading contact…';$('contactBody').textContent='';$('contactError').textContent='';$('toggleSuppression').disabled=true;
 if(!$('contactDialog').open)$('contactDialog').showModal();
 try{
  const data=await api('contacts/'+encodeURIComponent(id));if(version!==contactViewVersion)return;
  const c=data.contact,date=value=>{const d=new Date(value);return value&&Number.isFinite(d.getTime())?d.toLocaleString():'Not recorded';};
  $('contactTitle').textContent=c.first_name+' '+c.last_name;
  const fields=[['Title',c.title],['Company',c.company],['Location',[c.city,c.state,c.country].filter(Boolean).join(', ')],['Email',c.email],['Email status',c.email_status],['Email domain check',c.email_domain_check?.label||c.email_domain_check?.status?.replaceAll('_',' ')||'Not checked'],['Domain checked',date(c.email_domain_check?.checked_at)],['Phone',c.phone],['Phone status',c.phone_status],['Mobile phone (unverified)',c.mobile_phone],['Source',c.source],['Source observation date',c.source_observed_at||'Unknown'],['Added',date(c.created_at)],['Last updated',date(c.updated_at)],['Lists',data.lists.map(l=>l.name).join(', ')||'No lists'],['Email verifier',c.email_verification?.provider||'Not checked'],['Email checked',date(c.email_verification?.checked_at)],['Checked address',c.email_verification?.email],['Enrichment provider',c.enrichment?.provider],['Enriched',date(c.enrichment?.checked_at)]];
  $('contactBody').innerHTML='<dl class="contact-details">'+fields.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'Not provided')}</dd></div>`).join('')+'</dl>'+`<p>${c.suppressed?'Suppressed: excluded from exports and provider processing.':'Available for exports and provider processing.'}</p><p class="muted">Email verification expires after 30 days. Source and check history remain available after expiry.</p>`;
  $('contactBody').insertAdjacentHTML('beforeend','<h3>Data review</h3>'+((c.quality?.issues||[]).length?'<ul>'+c.quality.issues.map(issue=>`<li>${esc(issue.message)}</li>`).join('')+'</ul>':'<p>No completeness issues detected. This is not a factual-accuracy guarantee.</p>')+'<p class="muted">A valid email check measures deliverability at the time checked, not the person’s ownership or permission to contact them.</p><h3>Source history</h3>'+((c.source_history||[]).length?'<ol>'+c.source_history.map(item=>`<li><strong>${esc(item.source)}</strong> · ${esc(item.kind)}<br>Observed: ${esc(item.observed_at||'unknown')} · Imported: ${esc(date(item.imported_at))}${item.row?` · Line ${item.row}`:''}${item.url?`<br><a href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">Open source</a>`:''}${item.differing_fields?.length?`<br>Source differs; existing values retained: ${item.differing_fields.map(esc).join(', ')}`:''}</li>`).join('')+'</ol><p class="muted">The latest 20 source events are shown. Import reports retain row outcomes.</p>':'<p>No source history was recorded for this older record.</p>'));
  const reviews=(c.source_history||[]).filter(event=>event.kind==='manual_review'||event.resolution);
  if(reviews.length)$('contactBody').insertAdjacentHTML('beforeend','<details><summary>Correction and conflict decisions</summary>'+reviews.map(event=>`<article><p>${esc(event.reason||event.resolution?.reason||'')} - ${esc(date(event.resolution?.reviewed_at||event.imported_at))}</p>${event.resolution?`<p>Decision: ${esc(event.resolution.decision==='accept'?'Accepted source values':'Kept current values')}</p>`:''}${Object.entries(event.changes||{}).map(([key,value])=>`<p>${esc(key.replaceAll('_',' '))}: ${esc(value.before||'(empty)')} to ${esc(value.after||'(empty)')}</p>`).join('')}</article>`).join('')+'</details>');
  const fieldSources=Object.entries(c.field_sources||{});
  if(fieldSources.length)$('contactBody').insertAdjacentHTML('beforeend','<details><summary>Field origins</summary><dl class="contact-details">'+fieldSources.map(([field,source])=>`<div><dt>${esc(field.replaceAll('_',' '))}</dt><dd>${esc(source.source)}<br>Observed: ${esc(source.observed_at||'unknown')}${source.row?` · Line ${source.row}`:''}</dd></div>`).join('')+'</dl></details>');
  const editable=['first_name','last_name','title','company','company_domain','industry','seniority','city','state','country','email','phone','mobile_phone','linkedin_url'];
  $('contactBody').insertAdjacentHTML('beforeend','<details id="correctionPanel"><summary>Correct contact details</summary><form id="correctionForm"><p>Review identity before changing identifiers. Edited contact routes require verification again. Source history is retained.</p>'+editable.map(key=>`<label>${esc(key.replaceAll('_',' '))}<input name="${key}" value="${esc(c[key]||'')}" maxlength="1000" ${['first_name','last_name'].includes(key)?'required':''}></label>`).join('')+'<label>Reason or evidence reference<textarea name="reason" required maxlength="1000"></textarea></label><button type="submit">Save corrections</button></form></details>');
  $('correctionForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;if(button.disabled)return;button.disabled=true;try{const values=Object.fromEntries(new FormData(e.target));await api('contacts/'+encodeURIComponent(id),{fields:Object.fromEntries(editable.map(key=>[key,values[key]])),reason:values.reason,revision:c.edit_revision},'PATCH');await load();if(version===contactViewVersion)await showContact(id);notice('Corrections saved with review history.');}catch(error){if(version===contactViewVersion)$('contactError').textContent=error.message;}finally{button.disabled=false;}};
  const conflicts=(c.source_history||[]).map((event,index)=>({event,index})).filter(({event})=>event.proposed_values&&!event.resolution);
  if(conflicts.length){
   $('contactBody').insertAdjacentHTML('beforeend','<h3>Review conflicting source values</h3>'+conflicts.map(({event,index})=>`<article><p>${esc(event.source)} - ${esc(date(event.imported_at))}</p><table><thead><tr><th>Field</th><th>Current</th><th>Source proposes</th></tr></thead><tbody>${Object.entries(event.proposed_values).map(([key,value])=>`<tr><th>${esc(key.replaceAll('_',' '))}</th><td>${esc(c[key]||'Not provided')}</td><td>${esc(value)}</td></tr>`).join('')}</tbody></table><label>Review reason<input id="conflictReason${index}" maxlength="1000"></label><button type="button" data-conflict="${index}" data-decision="accept">Accept source values</button><button type="button" class="secondary" data-conflict="${index}" data-decision="keep">Keep current values</button></article>`).join(''));
   document.querySelectorAll('[data-conflict]').forEach(button=>button.onclick=async()=>{if(button.disabled)return;button.disabled=true;try{const index=Number(button.dataset.conflict);await api('contacts/'+encodeURIComponent(id),{resolve_history_index:index,decision:button.dataset.decision,reason:$('conflictReason'+index).value,revision:c.edit_revision},'PATCH');await load();if(version===contactViewVersion)await showContact(id);notice('Source conflict reviewed.');}catch(error){if(version===contactViewVersion)$('contactError').textContent=error.message;}finally{button.disabled=false;}});
  }
  $('contactError').textContent='';const toggle=$('toggleSuppression');toggle.disabled=false;toggle.textContent=c.suppressed?'Remove suppression':'Suppress contact';
  toggle.onclick=async()=>{if(toggle.disabled)return;toggle.disabled=true;try{await api('contacts/'+encodeURIComponent(id),{suppressed:!c.suppressed},'PATCH');await load();if(version===contactViewVersion)await showContact(id);notice(c.suppressed?'Suppression removed.':'Contact suppressed.');}catch(e){if(version===contactViewVersion){$('contactError').textContent=e.message;toggle.disabled=false;}}};
  if(!$('contactDialog').open)$('contactDialog').showModal();
 }catch(e){if(version===contactViewVersion){$('contactTitle').textContent='Contact unavailable';$('contactError').textContent=e.message;}}
}

$('importFormat').onchange=()=>{$('source').value=$('importFormat').value==='zoominfo'?'ZoomInfo CSV export':'';};

api('me').then(user=>{$('account').textContent=user.email;}).catch(()=>{});

$('qualityOpen').onclick=async()=>{
 $('qualityDialog').showModal();$('qualityContent').textContent='Loading quality report…';
 try{
  const {summary:s,sources,coverage,imports}=await api('data-quality');
  const cards=[['Contacts',s.contacts],['Current valid email checks',s.verified_emails],['Unverified emails',s.unverified_emails],['Invalid emails',s.invalid_emails],['Domain checks recorded',s.domain_checks],['Mail-route issues at last check',s.domain_issues],['Suppressed contacts',s.suppressed],['No contact route',s.no_contact_route],['Shared mailboxes',s.shared_mailboxes],['Source date unknown',s.source_date_unknown],['Source older than 180 days',s.source_older_than_180_days]];
  $('qualityContent').innerHTML='<dl class="quality-cards">'+cards.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${Number(value).toLocaleString()}</dd></div>`).join('')+'</dl><h3>Source import results</h3><p class="muted">Up to 50 source labels, ordered by latest import. Matched rows are repeat records, not new leads. These counts do not measure source accuracy.</p>'+(sources.length?'<div class="table-wrap"><table><thead><tr><th>Source</th><th>Imports</th><th>New</th><th>Matched</th><th>Conflicts</th><th>Rejected</th></tr></thead><tbody>'+sources.map(source=>`<tr><td>${esc(source.source)}</td><td>${source.imports}</td><td>${source.added}</td><td>${source.duplicates}</td><td>${source.conflicts}</td><td>${source.rejected}</td></tr>`).join('')+'</tbody></table></div>':'<p>No imports yet.</p>')+'<h3>Recent imports</h3><p class="muted">The latest 20 imports. Exact repeated uploads do not increase these counts.</p>'+imports.map(item=>`<div class="import-history"><button class="text-button" data-report="${esc(item.id)}">${esc(item.source)} · ${esc(new Date(item.created_at).toLocaleString())}</button><span>${item.summary.added} new · ${item.summary.conflicts} conflicts · ${item.summary.rejected} rejected</span></div>`).join('')+'<h3>Choose evidence appropriate to the field</h3><ul><li>Licensed exports provide contact candidates. Track the export and observation dates, and independently check deliverability.</li><li>Company staff pages can support a named professional’s role and published business channels. Retain the exact page and observation date.</li><li>SEC filings and DOL Form 5500 support their stated filing and employer-plan facts. They do not establish an individual’s retirement balance or transfer eligibility.</li><li>Search snippets, inferred fields and imported status labels remain unverified. A source URL alone does not validate a claim.</li></ul>';
  const coverageHTML='<h3>Current records by original source</h3><p class="muted">Up to 50 sources by contact count. Each contact belongs to its original source here; later contributions are recorded in its source history. Valid checks measure deliverability, not ownership or source accuracy.</p>'+(coverage.length?'<div class="table-wrap"><table><thead><tr><th>Source</th><th>Contacts</th><th>Emails</th><th>Valid checks</th><th>Invalid</th><th>Last domain issues</th><th>Unknown source date</th></tr></thead><tbody>'+coverage.map(row=>`<tr><td>${esc(row.source)}</td><td>${row.contacts}</td><td>${row.emails}</td><td>${row.valid_emails}</td><td>${row.invalid_emails}</td><td>${row.domain_issues}</td><td>${row.unknown_dates}</td></tr>`).join('')+'</tbody></table></div>':'<p>No contacts yet.</p>');
  $('qualityContent').insertAdjacentHTML('beforeend',coverageHTML);
  document.querySelectorAll('[data-report]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const report=await api('imports/'+encodeURIComponent(button.dataset.report));
   if(!$('archivedImportDialog')){
    document.body.insertAdjacentHTML('beforeend','<dialog id="archivedImportDialog"><div class="dialog-title"><h2>Saved import report</h2><button class="secondary" id="closeArchivedImport">Close</button></div><p id="archivedImportLabel"></p><p class="muted">This is the saved result at import time. Current contact data may have changed.</p><p id="archivedImportResult"></p><div id="archivedImportBody"></div><button id="downloadArchivedImport" class="secondary">Download row report</button></dialog>');
    $('closeArchivedImport').onclick=()=>$('archivedImportDialog').close();
   }
   $('archivedImportLabel').textContent=report.source+' · '+new Date(report.created_at).toLocaleString();
   renderImportReport(report.result,{archived:true});$('downloadArchivedImport').hidden=!report.result.rows?.length;$('downloadArchivedImport').onclick=()=>downloadReport(report.result);$('archivedImportDialog').showModal();
  }catch(error){notice(error.message,true);}finally{button.disabled=false;}});
 }catch(error){$('qualityContent').textContent=error.message;}
};
