import {initProviderUI} from './prospect-jobs-client.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let offset=0,contacts=[],lists=[],searches=[],loadVersion=0;const selected=new Set();
const notice=(message,error=false)=>{$('notice').textContent=message;$('notice').classList.toggle('error',error);};
async function api(path,body,method=body?'POST':'GET'){const r=await fetch('/api/prospect/'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(r.status===401){location.href='/login';throw Error('Sign in to continue.');}if(!r.ok){let data;try{data=await r.json();}catch{}throw Error(data?.detail||'Request failed.');}return r.headers.get('Content-Type')?.includes('text/csv')?r.blob():r.json();}
const filters=()=>({...Object.fromEntries(new FormData($('filters'))),list_id:$('listFilter').value});
function selection(){ $('selectedCount').textContent=selected.size+' selected';for(const id of ['export','addListOpen','removeList'])$(id).disabled=!selected.size;}
async function load(){const version=++loadVersion;try{const data=await api('contacts?'+new URLSearchParams({...filters(),offset,limit:50}));if(version!==loadVersion)return;contacts=data.contacts;$('total').textContent=data.total.toLocaleString()+' contacts in your directory';$('resultTitle').textContent=lists.find(l=>l.id===$('listFilter').value)?.name||'All contacts';$('removeList').hidden=!$('listFilter').value;
 $('table').innerHTML=contacts.length?'<table><thead><tr><th><input id="selectPage" type="checkbox" aria-label="Select this page"></th><th>Contact</th><th>Company</th><th>Email</th><th>Phone</th><th>Location</th></tr></thead><tbody>'+contacts.map(c=>`<tr><td><input type="checkbox" data-id="${esc(c.id)}" aria-label="Select ${esc(c.first_name+' '+c.last_name)}" ${selected.has(c.id)?'checked':''}></td><td><button class="text-button contact-name" data-contact="${esc(c.id)}">${esc(c.first_name+' '+c.last_name)}</button><small>${esc(c.title||'Title not provided')}</small>${c.linkedin_url?`<a href="${esc(c.linkedin_url)}" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>`:''}${c.suppressed?'<span class="badge suppressed">Suppressed</span>':''}</td><td>${esc(c.company||'—')}<small>${esc(c.industry)}</small></td><td>${esc(c.email||'No email')}<br><span class="badge ${esc(c.email_status)}">${esc(c.email_status)}</span></td><td>${esc(c.phone||'No phone')}<br><span class="badge">${esc(c.phone_status)}</span></td><td>${esc([c.city,c.state,c.country].filter(Boolean).join(', ')||'—')}<small>${esc(c.source)}</small></td></tr>`).join('')+'</tbody></table>':'<div class="empty"><h2>No contacts match this view</h2><p>Import an authorized contact list or adjust your filters to begin.</p></div>';
 document.querySelectorAll('[data-contact]').forEach(el=>el.onclick=()=>showContact(el.dataset.contact));document.querySelectorAll('[data-id]').forEach(e=>e.onchange=()=>{e.checked?selected.add(e.dataset.id):selected.delete(e.dataset.id);selection();});if($('selectPage')){$('selectPage').checked=contacts.every(c=>selected.has(c.id));$('selectPage').onchange=e=>{contacts.forEach(c=>e.target.checked?selected.add(c.id):selected.delete(c.id));document.querySelectorAll('[data-id]').forEach(el=>el.checked=e.target.checked);selection();};}
 $('pageLabel').textContent=data.total?`${offset+1}–${Math.min(offset+50,data.total)} of ${data.total}`:'0 contacts';$('previous').disabled=offset===0;$('next').disabled=offset+50>=data.total;selection();
 }catch(e){if(version===loadVersion)notice(e.message,true);}}
async function loadLists(){lists=(await api('lists')).lists;for(const id of ['listFilter','importList','addList']){const value=$(id).value;$(id).innerHTML=(id==='addList'?'':`<option value="">${id==='listFilter'?'All contacts':'No list'}</option>`)+lists.map(l=>`<option value="${esc(l.id)}">${esc(l.name)} (${l.contacts})</option>`).join('');if([...$(id).options].some(o=>o.value===value))$(id).value=value;}}
async function loadSearches(){
 searches=(await api('saved-searches')).searches;
 $('searches').innerHTML=searches.length?searches.map(s=>`<div class="saved-search"><button class="text-button" data-search="${esc(s.id)}">${esc(s.name)}</button><button class="text-button" data-delete-search="${esc(s.id)}" aria-label="Delete saved search ${esc(s.name)}">Delete</button></div>`).join(''):'<p class="muted">Save filters you use often.</p>';
 document.querySelectorAll('[data-search]').forEach(el=>el.onclick=()=>{const f=searches.find(s=>s.id===el.dataset.search).filters;$('filters').reset();for(const [key,value] of Object.entries(f)){const input=$('filters').elements.namedItem(key);if(input)input.value=value;}$('listFilter').value=f.list_id||'';offset=0;selected.clear();load();});
 document.querySelectorAll('[data-delete-search]').forEach(el=>el.onclick=async()=>{el.disabled=true;try{await api('saved-searches/'+encodeURIComponent(el.dataset.deleteSearch),undefined,'DELETE');await loadSearches();notice('Saved search deleted.');}catch(e){el.disabled=false;notice(e.message,true);}});
}
$('filters').onsubmit=e=>{e.preventDefault();offset=0;selected.clear();load();};$('filters').onreset=()=>setTimeout(()=>{offset=0;selected.clear();load();},0);$('listFilter').onchange=()=>{offset=0;selected.clear();load();};$('previous').onclick=()=>{offset=Math.max(0,offset-50);load();};$('next').onclick=()=>{offset+=50;load();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
for(const [button,dialog] of [['importOpen','importDialog'],['newListOpen','listDialog'],['saveSearchOpen','searchDialog']])$(button).onclick=()=>$(dialog).showModal();
$('addListOpen').onclick=()=>{if(!lists.length)return notice('Create a list first.');$('addDialog').showModal();};
async function submit(event,errorId,operation){event.preventDefault();const b=event.submitter;b.disabled=true;$(errorId).textContent='';try{await operation();}catch(e){$(errorId).textContent=e.message;}finally{b.disabled=false;}}
$('listForm').onsubmit=e=>submit(e,'listError',async()=>{await api('lists',{name:$('listName').value});await loadLists();$('listDialog').close();$('listForm').reset();notice('List created.');});
$('searchForm').onsubmit=e=>submit(e,'searchError',async()=>{await api('saved-searches',{name:$('searchName').value,filters:filters()});await loadSearches();$('searchDialog').close();$('searchForm').reset();notice('Search saved.');});
$('addForm').onsubmit=e=>submit(e,'addError',async()=>{await api('lists/'+encodeURIComponent($('addList').value)+'/members',{ids:[...selected]});await loadLists();$('addDialog').close();notice('Selected contacts added to the list.');});
$('removeList').onclick=async()=>{try{await api('lists/'+encodeURIComponent($('listFilter').value)+'/members',{ids:[...selected]},'DELETE');selected.clear();await loadLists();await load();notice('Contacts removed from this list; they remain in your directory.');}catch(e){notice(e.message,true);}};
$('importForm').onsubmit=e=>submit(e,'importResult',async()=>{const file=$('csvFile').files[0];if(!file||file.size>4000000)throw Error('Choose a CSV up to 4 MB.');const r=await api('import',{csv:await file.text(),format:importFormat.value,source:$('source').value,list_id:$('importList').value||undefined});await loadLists();offset=0;await load();const message=r.replayed?'This exact import was already processed.':`${r.added} added · ${r.duplicates} duplicates · ${r.conflicts} identity conflicts · ${r.rejected} rejected.`;$('importResult').textContent=message+(r.errors?.length?' '+r.errors.map(x=>`Row ${x.row}: ${x.message}`).join(' '):'');notice(message);});
$('export').onclick=async()=>{try{const blob=await api('export',{ids:[...selected]});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='prospectpilot-contacts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Export ready. Suppressed contacts were omitted.');}catch(e){notice(e.message,true);}};
try{await Promise.all([loadLists(),loadSearches()]);await load();notice('Your contact workspace is ready.');}catch(e){notice(e.message,true);}

initProviderUI({api,selected,filters,getLists:()=>lists,refresh:async()=>{await loadLists();await load();},notice}).catch(e=>notice(e.message,true));

// List management uses the existing owner-scoped API and leaves contacts intact.
const manageButton=document.createElement('button');manageButton.className='secondary';manageButton.textContent='Manage list';$('newListOpen').after(manageButton);
document.body.insertAdjacentHTML('beforeend','<dialog id="manageListDialog"><form id="manageListForm"><div class="dialog-title"><h2>Manage list</h2><button type="button" class="secondary" id="closeManageList">Close</button></div><label>List<select id="managedList" required></select></label><label>List name<input id="manageListName" required maxlength="100"></label><p id="manageListError" role="alert"></p><button type="submit">Save name</button><hr><p>Deleting this list removes its memberships. Contacts stay in your directory. Saved searches using it will search all contacts.</p><button type="button" class="secondary" id="deleteList">Delete list</button></form></dialog>');
const managedName=()=>{$('manageListName').value=lists.find(l=>l.id===$('managedList').value)?.name||'';};
manageButton.onclick=()=>{if(!lists.length)return notice('Create a list first.');$('managedList').innerHTML=lists.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');if($('listFilter').value)$('managedList').value=$('listFilter').value;managedName();$('manageListError').textContent='';$('manageListDialog').showModal();};
$('managedList').onchange=managedName;$('closeManageList').onclick=()=>$('manageListDialog').close();
$('manageListForm').onsubmit=e=>submit(e,'manageListError',async()=>{await api('lists/'+encodeURIComponent($('managedList').value),{name:$('manageListName').value},'PATCH');await loadLists();await load();$('manageListDialog').close();notice('List renamed.');});
$('deleteList').onclick=async()=>{const button=$('deleteList');button.disabled=true;try{const id=$('managedList').value;await api('lists/'+encodeURIComponent(id),undefined,'DELETE');if($('listFilter').value===id){$('listFilter').value='';offset=0;selected.clear();}await Promise.all([loadLists(),loadSearches()]);await load();$('manageListDialog').close();notice('List deleted. Its contacts remain in your directory.');}catch(e){$('manageListError').textContent=e.message;}finally{button.disabled=false;}};


let contactViewVersion=0;
async function showContact(id){
 const version=++contactViewVersion;
 try{
  const data=await api('contacts/'+encodeURIComponent(id));if(version!==contactViewVersion)return;
  const c=data.contact,date=value=>{const d=new Date(value);return value&&Number.isFinite(d.getTime())?d.toLocaleString():'Not recorded';};
  if(!$('contactDialog')){document.body.insertAdjacentHTML('beforeend','<dialog id="contactDialog"><div class="dialog-title"><h2 id="contactTitle">Contact details</h2><button class="secondary" id="closeContact">Close</button></div><div id="contactBody"></div><p id="contactError" role="alert"></p><button id="toggleSuppression"></button></dialog>');$('closeContact').onclick=()=>$('contactDialog').close();}
  $('contactTitle').textContent=c.first_name+' '+c.last_name;
  const fields=[['Title',c.title],['Company',c.company],['Location',[c.city,c.state,c.country].filter(Boolean).join(', ')],['Email',c.email],['Email status',c.email_status],['Phone',c.phone],['Phone status',c.phone_status],['Source',c.source],['Added',date(c.created_at)],['Last updated',date(c.updated_at)],['Lists',data.lists.map(l=>l.name).join(', ')||'No lists'],['Email verifier',c.email_verification?.provider||'Not checked'],['Email checked',date(c.email_verification?.checked_at)],['Checked address',c.email_verification?.email],['Enrichment provider',c.enrichment?.provider],['Enriched',date(c.enrichment?.checked_at)]];
  $('contactBody').innerHTML='<dl class="contact-details">'+fields.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'Not provided')}</dd></div>`).join('')+'</dl>'+`<p>${c.suppressed?'Suppressed: excluded from exports and provider processing.':'Available for exports and provider processing.'}</p><p class="muted">Email verification expires after 30 days. Source and check history remain available after expiry.</p>`;
  $('contactError').textContent='';const toggle=$('toggleSuppression');toggle.disabled=false;toggle.textContent=c.suppressed?'Remove suppression':'Suppress contact';
  toggle.onclick=async()=>{toggle.disabled=true;try{await api('contacts/'+encodeURIComponent(id),{suppressed:!c.suppressed},'PATCH');await load();await showContact(id);notice(c.suppressed?'Suppression removed.':'Contact suppressed.');}catch(e){$('contactError').textContent=e.message;toggle.disabled=false;}};
  if(!$('contactDialog').open)$('contactDialog').showModal();
 }catch(e){notice(e.message,true);}
}

$('importFormat').onchange=()=>{$('source').value=$('importFormat').value==='zoominfo'?'ZoomInfo CSV export':'';};
