export const SOURCE_CATALOG = [
  {id:'form5500', name:'DOL Form 5500', scope:'Employer plans', cost:'No data credits', mode:'catalog', supports:'Plan assets, participants, separated participants, reported in-service distributions', limit:'Employer evidence only. It does not establish an individual balance or eligibility.', url:'https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/public-disclosure/foia/form-5500-datasets'},
  {id:'public_web', name:'Company websites & public biographies', scope:'People', cost:'No data credits', mode:'automatic', supports:'Named professionals, published contact links, age and career evidence for review', limit:'Honors access restrictions; missing or blocked pages remain visible.', url:'https://prospectpilot.io'},
  {id:'warn', name:'WARN notices', scope:'Employers', cost:'No data credits', mode:'automatic', supports:'Employer events and publication dates', limit:'State coverage varies; a notice never means a named employee lost their job.', url:'https://dol.ny.gov/warn-dashboard'},
  {id:'sec', name:'SEC EDGAR', scope:'Public company filings', cost:'No data credits', mode:'automatic', supports:'Recent proxy filings and executive age evidence for review', limit:'Executive coverage; filings do not prove residence, retirement accounts, or contactability.', url:'https://www.sec.gov/search-filings/edgar-application-programming-interfaces'},
  {id:'web_search', name:'Licensed web search', scope:'People & companies', cost:'Configured price per query', mode:'optional', supports:'Broad web discovery through a server-configured Brave Search subscription', limit:'Disabled without configuration or budget. Search snippets are candidates, not verified evidence.', url:'https://brave.com/search/api/'},
  {id:'zoominfo', name:'ZoomInfo', scope:'Professional contacts', cost:'Your own subscription / imported cost', mode:'import', supports:'CSV and ListMatch exports through the existing provider workflow', limit:'No shared subscription; import does not verify age or retirement funds.', url:'https://www.zoominfo.com'},
  {id:'wealthfeed', name:'WealthFeed', scope:'Licensed provider data', cost:'Your subscription / imported cost', mode:'import', supports:'Existing provider import and matching workflow', limit:'Recorded balances or estimates remain provider-reported until reviewed.', url:'https://wealthfeed.com'},
  {id:'linkedin', name:'LinkedIn', scope:'Professional profiles', cost:'Manual import; subscription costs recorded separately', mode:'import', supports:'Profile URLs, user-provided snapshots and permitted exports', limit:'OpenID Connect identifies the signed-in member; it grants no prospect-search access.', url:'https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2'},
  {id:'whitepages', name:'Whitepages / Trestle', scope:'Contact validation', cost:'Licensed lookup', mode:'import', supports:'User-authorized licensed validation results', limit:'Paid lookups require the user’s provider configuration and budget.', url:'https://trestleiq.com'},
  {id:'fec', name:'FEC contributor records', scope:'Excluded', cost:'Not used', mode:'excluded', supports:'None in the prospect pipeline', limit:'Individual contributor information is excluded from prospect discovery, scoring, and exports because commercial use is restricted.', url:'https://www.fec.gov/updates/sale-or-use-contributor-information/'},
  {id:'people_search', name:'FastPeopleSearch / FamilyTreeNow', scope:'Not enabled', cost:'Not used', mode:'excluded', supports:'None in the automatic pipeline', limit:'No automated aggregation of personal household or relative records. Use professional or participant-provided evidence.', url:''},
];
